### ISSUE TITLE
Most components have lost wiring in their outputs

### ISSUE THREAD

**Issue by Sonderwoods** [mcneel/rhino.inside-revit#1018]
**Versions**

> RiR:  1.17.8620.27747 (2023-08-08)
> Rhino: 7 SR33
> Revit: 2023.01

**Describe the bug**
There's a bug in the parameter objects (input output) of many components.
This causes all of my grasshopper script to loose their wires. Most RiR components outputs are not connected to the objects that they were.

This is super annoying and causing a lot of remaking on large scripts

So far its happening on the following components:
- Element Name
- Query Elements
- Element Parameter
- Element Geometry

![image](https://github.com/mcneel/rhino.inside-revit/assets/19936679/247bc911-8d42-4889-bdba-890bf46da32b)

**To Reproduce**
Try opening 3-4 months old scripts

**Screenshots**
![image](https://github.com/mcneel/rhino.inside-revit/assets/19936679/42b3e1da-f193-47a8-9c39-6a5da15da7de)

![image](https://github.com/mcneel/rhino.inside-revit/assets/19936679/9b0da840-830e-44ea-9ddb-0698dc4560b1)
![image](https://github.com/mcneel/rhino.inside-revit/assets/19936679/4047cd1e-430c-44d0-859f-7858d68d4d97)

![image](https://github.com/mcneel/rhino.inside-revit/assets/19936679/2d9429bc-25e1-4ffb-9124-c1636ddcb98e)

upon on loading a document (which worked a few months ago)
![image](https://github.com/mcneel/rhino.inside-revit/assets/19936679/1fbcef95-3e5f-464e-8121-bcec51433a1c)
![image](https://github.com/mcneel/rhino.inside-revit/assets/19936679/d71dad70-b7c5-45d7-9e6e-2254a9bea899)
![image](https://github.com/mcneel/rhino.inside-revit/assets/19936679/35670da5-7a7d-4961-b643-acb8faff68f2)

**Comment by kike-garbo** [comment]
Hi @Sonderwoods,

Can you share any of those .gh files that are failing?
