### ISSUE TITLE
Host Grid - Deconstruct Grid fails when Window are nested in the curtain wall. 

### ISSUE THREAD

**Issue by japhyw** [mcneel/rhino.inside-revit#1024]
Tested in:
Rhino: 7.34.23267.11001 (Rhino 7)
Revit: 2023.1.20 (23.1.20.70)

![image](https://github.com/mcneel/rhino.inside-revit/assets/87487580/9959af63-3f20-4ef1-85c7-f34918ae47ca)

Example file:  Removing Doors and Windows from the selected Curtain Wall clears up the error. 
[RiR V2023_Hosted-Windows.zip](https://github.com/mcneel/rhino.inside-revit/files/12850649/RiR.V2023_Hosted-Windows.zip)
In a fresh file a simple example with the same windows works.

**Comment by japhyw** [comment]
Another request to get this fixed. https://discourse.mcneel.com/t/analize-curtain-walls-component-rhino-inside/160495/10?u=japhy

**Comment by kike-garbo** [comment]
Fixed in 1.24
