### ISSUE TITLE
Method not found error on Revit 2023 new component family - Rhino 8

### ISSUE THREAD

**Issue by japhyw** [mcneel/rhino.inside-revit#1027]
Reported on discourse https://discourse.mcneel.com/t/new-component-issue-with-untrimmed-surfaces/167261

Tested and confirmed on: 
Rhino.Inside Revit: 1.18.8684.11310 (2023-10-11T06:17:00)
Rhino: 8.0.23290.19001 (Rhino 8)
Revit: 2023.1.20 (23.1.20.70)
CLR: 4.0.30319.42000 (4.8.9181.0)
OS: Microsoft Windows NT 10.0.19045.0

![image](https://github.com/mcneel/rhino.inside-revit/assets/87487580/49f6a132-b53b-4285-925a-e26941e22c21)

1. RhinoInside.Revit: Method not found: 'Void Rhino.FileIO.FileDwgWriteOptions.set_ColorMethod(eColorMethod)'.

**Comment by kike-garbo** [comment]
Fixed on https://github.com/mcneel/rhino.inside-revit/pull/1029
