### ISSUE TITLE
Eto platform is null when trying to open Options

### ISSUE THREAD

**Issue by eirannejad** [mcneel/rhino.inside-revit#1028]
When "LadyBug Pollination For Revit" tools is installed:

- Open Revit
- Open RIR Tab, and click on More -> Options

This error happens:

![Revit_xUlStzk1YP](https://github.com/mcneel/rhino.inside-revit/assets/8197916/00ae8e89-915f-40df-8b6f-7da060ada823)

Test on Revit 2023
Rhino 7.33.23248.13001, 2023-09-05
Eto 2.7.0

RE:
https://discourse.pollination.cloud/t/conflict-between-the-pollination-plugin-and-rir/2483

**Comment by mostaphaRoudsari** [comment]
I was able to recreate the issue today with the latest version of Rhino 8, Revit 2024, and Rhino.Inside.Revit that @japhyw shared for the AEC Tech workshop.

**Error message**
<img width="411" alt="image" src="https://github.com/mcneel/rhino.inside-revit/assets/2915573/c0d5f980-83f0-4b48-b13a-8547fefde19f">

**Installer versions**

<img width="295" alt="image" src="https://github.com/mcneel/rhino.inside-revit/assets/2915573/4dc4134d-b1f8-43b3-bc87-9ea104d3ea0b">


This has been a blocker for us to investigate the opportunities for using the Pollination Revit plugin in RiR. It would be great if someone can have a closer look at this issue and let us know what we need to change on our end. Thanks!
