### ISSUE TITLE
Errors in Appearance Asset Analyze and Modify components 

### ISSUE THREAD

**Issue by japhyw** [mcneel/rhino.inside-revit#1049]
Getting an image from an existing material that has a image texture give this error.

![image](https://github.com/mcneel/rhino.inside-revit/assets/87487580/d4572d28-81a4-4005-97c7-97b0f0c358cc)

Tested in 

Rhino: 8.3.23333.06001 (Rhino 8)
Revit: 2023.1.20 (23.1.20.70)
CLR: 4.0.30319.42000 (4.8.9181.0)
OS: Microsoft Windows NT 10.0.19045.0

**Comment by kike-garbo** [comment]
This is how this component is mean to work.
I think we need more components to deconstruct other types of assets.
