### ISSUE TITLE
'Define Shared Parameter' needs to get parameter group

### ISSUE THREAD

**Issue by eirannejad** [mcneel/rhino.inside-revit#107]
**Is your feature request related to a problem? Please describe.**
Currently the `AddParameterKey.ByName` component always creates the parameter under the `Data` category. 

**Describe the solution you'd like**
This component needs to be expanded to include the rest of the parameter creation options (type, group, ...)

**Additional context**
Related to [Forum discussion](https://discourse.mcneel.com/t/change-the-parametergroup-of-a-parameter/94754)

**Comment by stoltm** [comment]
@eirannejad 
I think that it would be very important to be able to access existing parameters in particular.
It woudl be essential to be able to access predefined ifc-Parameters or params like "Volume" in particular.
