### ISSUE TITLE
Add Wall as Reference to Annotation throws exemption

### ISSUE THREAD

**Issue by japhyw** [mcneel/rhino.inside-revit#1071]
Reported on Slack by Jessesn

https://mcneel.slack.com/archives/CD5FDC61Z/p1706066999022319

Input of a Wall as Reference for Annotation throws 'object instance not found error'

tested it in Revit2023, and the client tested it in Revit2024, both Rhino 7.35 and Rhino 8.3

Expectation is to accept as a reference or have not throw an exemption and show an instructional message.

**Comment by kike-garbo** [comment]
This is working on v1.22, I guess was tested before.
![image](https://github.com/mcneel/rhino.inside-revit/assets/3530512/08653025-b07a-47b3-9ab4-f8880593662b)
