### ISSUE TITLE
Change Name of Phase Element

### ISSUE THREAD

**Issue by japhyw** [mcneel/rhino.inside-revit#1072]
This looks to inherit from Element, but getting an error trying to change the Phase Element Name

![image](https://github.com/mcneel/rhino.inside-revit/assets/87487580/fdc9c86e-b118-4e7d-95d8-a863d3223d36)

https://www.revitapidocs.com/2017.1/df546e3c-360e-ca2d-a5ba-982e83c1b979.htm

Rhino.Inside Revit: 1.19.8753.16429 (2023-12-19T09:07:38)

Rhino: 8.5.24031.02001 (Rhino 8)
Revit: 2024.0 (24.0.4.427)

**Comment by kike-garbo** [comment]
It is a Revit API limitation.
