### ISSUE TITLE
Add Multisegement Grid support

### ISSUE THREAD

**Issue by japhyw** [mcneel/rhino.inside-revit#1075]
Users request the ability to add Multi Segment Grids via native Rhino.Inside.Revit components

https://discourse.mcneel.com/t/create-multi-segmented-grid-in-revit-from-multi-segmented-curve/111662/5

https://www.revitapidocs.com/2019/8488ef7c-7669-26a7-8088-dd78e96850de.htm

**Comment by kike-garbo** [comment]
Added in v1.21
