### ISSUE TITLE
New component that sets a view range offset and level

### ISSUE THREAD

**Issue by japhyw** [mcneel/rhino.inside-revit#1081]
Requested on discourse

https://discourse.mcneel.com/t/rhino-inside-revit-set-view-range/169262/4

https://www.revitapidocs.com/2019/7edc5f13-a5fa-5c7a-9a03-ac6cbed1f005.htm

https://boostyourbim.wordpress.com/2012/12/22/using-3d-section-box-to-set-plan-views-view-range/

**Comment by kike-garbo** [comment]
Done in 1.21
