### ISSUE TITLE
Arc Length Dimension not returning proper length

### ISSUE THREAD

**Issue by japhyw** [mcneel/rhino.inside-revit#1082]
Is the right overload being used?  The ARC Length generated is way off. 

https://discourse.mcneel.com/t/how-can-i-add-the-arc-length-in-rhinoinside/177313/4

![image](https://github.com/mcneel/rhino.inside-revit/assets/87487580/e207af12-d70e-42db-9e4d-efaa696bdc7a)

**Comment by kike-garbo** [comment]
This component measures the angle not the Length.
We have added 'Add Arc Length Dimension' component on v1.23 for measuring length. (Only works on 2025 or above).
