### ISSUE TITLE
rhino 8 cast view to material (image)

### ISSUE THREAD

**Issue by japhyw** [mcneel/rhino.inside-revit#1087]
Rhino 8 Preview is black

![image](https://github.com/mcneel/rhino.inside-revit/assets/87487580/704b54b1-e974-4f09-b55f-4335c3d36236)

In Rhino 7 

![image](https://github.com/mcneel/rhino.inside-revit/assets/87487580/be17294a-109f-43d4-bc1c-8eee911b5ff2)

**https://discourse.mcneel.com/t/bake-title-block-geometry/166114/9**

**Comment by kike-garbo** [comment]
Fixed on Rhino 8.12
