### ISSUE TITLE
Shortcut doesnt work in GH (rhino.inside)

### ISSUE THREAD

**Issue by SMazlan** [mcneel/rhino.inside-revit#109]
Hi, i just updated my Rhino.Inside version 0.0.7324.23218 
after finished the update, my GH shortcut doesnt work anymore. 
example : i cant use the delete button in GH. 

In addition, shortcut delete in rhino also doesnt work. but its okay because still can type delete command. 

This only happen when using Rhino.Inside. Using rhino wip and Gh alone the shortcut is working fine. Thank you

**Comment by kike-garbo** [comment]
This is fixed in the latest Rhino WIP (7.0.20021.12255, 01/21/2020)
You need to update to that version of Rhino.
