### ISSUE TITLE
Rhinoinsode Revit installer needs to be signed for a smooth download install

### ISSUE THREAD

**Issue by scotttd** [mcneel/rhino.inside-revit#11]
Windows defender displays a warning when the installer is downloaded.  This requires the More Info button to be pressed to even find the download button.

**Comment by pearswj** [comment]
CI build moved to McNeel's internal TeamCity server so that the DLLs and installer can be signed with our certificate. The AppVeyor build will be kept around so that it's still possible for external contributors to view the build logs online.
