### ISSUE TITLE
Add optional Visible Element Tracking State to components that allow tracking

### ISSUE THREAD

**Issue by japhyw** [mcneel/rhino.inside-revit#1109]
Requested on Discourse. 

https://discourse.mcneel.com/t/wish-display-info-about-components-tracking-mode-underneath-the-capsule/179937

![image](https://github.com/mcneel/rhino.inside-revit/assets/87487580/e79f2329-0aef-4563-979b-8d214ec87038)

Having an indicator of the object tracking state would be helpful for people who change states and need to go check all components by right clicking on each one.

**Comment by kike-garbo** [comment]
Implemented on v1.22
