### ISSUE TITLE
Phase Filter Component requires "Element On Phase Status", but it's undocumented how to find this

### ISSUE THREAD

**Issue by Sonderwoods** [mcneel/rhino.inside-revit#1128]
![image](https://github.com/mcneel/rhino.inside-revit/assets/19936679/f03f96fb-a33c-49a0-aea2-a1bb614e0aa6)

Perhaps some info in the param description would be beneficial

**Comment by Sonderwoods** [comment]
Quickfix: Ended up inputting a number and trial and error


![image](https://github.com/mcneel/rhino.inside-revit/assets/19936679/7fa2c2f4-e011-49bd-8959-d9374c037c92)

**Comment by japhyw** [comment]
The forum will get you a quicker response to questions. 

Right click on the component to select the value or expose the picker.

![image](https://github.com/mcneel/rhino.inside-revit/assets/87487580/9fd5cb7d-409e-4a0a-9d17-4fa9b6b9df72)


![image](https://github.com/mcneel/rhino.inside-revit/assets/87487580/22e71240-8b48-4f38-bbe7-3732388380fe)
