### ISSUE TITLE
Reproducible crash with adding Wall Material Takeoff after adding geometry cache and switching to a 3d view. 

### ISSUE THREAD

**Issue by japhyw** [mcneel/rhino.inside-revit#1133]
See this post for details and files to reproduce.

https://discourse.mcneel.com/t/reproduceable-crash-behavior/184426

Reproducible crash with adding Wall Material Takeoff after adding geometry cache and switching to a 3d view.

**Comment by japhyw** [comment]
Similar report 
https://discourse.mcneel.com/t/transferring-rhino-as-mass-crashes-revit/187740/3

**Comment by japhyw** [comment]
user reports not crashing when switching view tabs with Element Tracking Disabled.   https://discourse.mcneel.com/t/revit-constantly-crashing-with-rhino-inside/184991/5?u=japhy

**Comment by kike-garbo** [comment]
Same as #1161
Fixed on #1163
