### ISSUE TITLE
Missing Appearance Asset Info (regression)

### ISSUE THREAD

**Issue by japhyw** [mcneel/rhino.inside-revit#1149]
Reported on SupportBee

User upgraded RiR and lost the Keyword and Description inputs on the Modify Appearance Asset component 

https://mcneel.supportbee.com/tickets/48175734

![image](https://github.com/user-attachments/assets/0a99e0eb-bd4c-4888-9ddb-47454ab43a22)

**Comment by japhyw** [comment]
This is a reported change from 

Rhino v8.7.24134.03001 to  Rhino v8.8.24170.13001

**Comment by kike-garbo** [comment]
We had a problem with the previous setup of the 'Modify Appearance Asset' and it only works with Generic materials.

![image](https://github.com/user-attachments/assets/1b84d2f5-c661-4881-a924-b7e9baafd62f)

'Appearance Asset Identity' was introduced in v1.22 to fix that issue and enable this functionality on any material even if it is not Generic

![image](https://github.com/user-attachments/assets/b83899b2-03a4-40b6-b73e-033f093ca162)
