### ISSUE TITLE
User has to replace older component to clear apparent bug.

### ISSUE THREAD

**Issue by japhyw** [mcneel/rhino.inside-revit#1152]
Reported on Discourse

https://discourse.mcneel.com/t/revit-subcategory-management-in-a-component-family-workflow/187816/7?u=japhy

User initially reported having inconsistent results with Add SubCategory, after troubleshooting replacing the component cleared up the issue.  The user suspects that the older component wasn't getting auto-updated.

**Comment by kike-garbo** [comment]
'Family From' and 'Add SubCategory' components are exactly like they were on 1.0.
We did not implement upgrade-downgrade to files save before 1.0.
