### ISSUE TITLE
Creating revit analytical lines and surface from RIR

### ISSUE THREAD

**Issue by ThatMetaverseArchitect** [mcneel/rhino.inside-revit#1155]
I think it would be great if we can create analytical line and surfaces from the grasshopper geometries.

![creatingAnalyticalModel](https://github.com/user-attachments/assets/c98c2a39-b34f-444e-bd20-df3faeaeb31f)

dynamo has already components for this workflow

I just thought that RiR could also have components for the analyze panel.

**Comment by kike-garbo** [comment]
Implemented on 1.27

**Comment by ThatMetaverseArchitect** [comment]
Great news!! Thanks Kike for the updates!
