### ISSUE TITLE
Can't add second door to a new Wall 

### ISSUE THREAD

**Issue by Jessesn** [mcneel/rhino.inside-revit#1176]
**Versions**

> Rhino.Inside: 1.23.8998.19322
> Rhino: 8.10
> Revit: 2024

**Describe the bug**
I found I can't insert second door to a wall that created by NewComponentFamily of RIR. 
I also can't insert any door to this wall after I delete the previous inserted door.

https://github.com/user-attachments/assets/85396681-0c55-4be1-91e5-9a813158b30b

Pls [click here](https://drive.google.com/file/d/1EXT4ozr9HcWROJQlXaXQEMiCF7AUcV1B/view?usp=sharing) to download my test file.

**Comment by japhyw** [comment]
Hi Jessesn, 

The only way to create a 'Real' wall (one that accepts Doors normally) is to duplicate and edit a type.
