### ISSUE TITLE
Add Reference Line : Curve should be C1 Continuous

### ISSUE THREAD

**Issue by Jessesn** [mcneel/rhino.inside-revit#1191]
**Versions**

> Rhino.Inside: 1.23.8998.19322
> Rhino: 8.11
> Revit: 2024

I tried to a set of curves with curvature continuity  as the import curves to the component Add Reference Line, still got a error note " Curve should be C1 Continuous"

![AddReferenceLineIssue](https://github.com/user-attachments/assets/9715e499-ee6c-430f-9d98-257485e86ac3)

Here are the steps for my test. Thanks.

https://github.com/user-attachments/assets/bc26422b-4452-4431-b7f9-87ef526bfeee

[AddReferenceLineIssue.zip](https://github.com/user-attachments/files/17004509/AddReferenceLineIssue.zip)

**Comment by kike-garbo** [comment]
Now it shows a more accurate error message.
![image](https://github.com/user-attachments/assets/f8d5f500-f61a-4b1b-a352-2d60b9839170)
