### ISSUE TITLE
Create new 3D View In Revit

### ISSUE THREAD

**Issue by scotttd** [mcneel/rhino.inside-revit#12]
Can we match views in Revit from a Rhino view?  Add a view, camera location, target etc?

**Comment by fraguada** [comment]
We've had another request for this. From Rhino "Named Views" to Revit.

**Comment by kike-garbo** [comment]
We already have some work prototyped in this area for 3D Views.

- [x] Camera parameter (Supports any Grasshopper transform existing component)
- [x] Construct Camera
- [x] Deconstruct Camera
- [ ] Get Viewport Camera (From Rhino)
- [ ] Set Viewport Camera (To Rhino)
- [x] Default 3D View (Per user)
- [x] Add 3D View
- [x] View Camera (Get-Set)
- [x] View Zoom extents (To a BoundingBox)

**Comment by kike-garbo** [comment]
This is possible in Rhino 8.
![image](https://github.com/mcneel/rhino.inside-revit/assets/3530512/90266dab-f9fc-468b-8fb2-2d4d0e890a5a)
