### ISSUE TITLE
Host Grids no longer returns Sloped Glazing Grids

### ISSUE THREAD

**Issue by japhyw** [mcneel/rhino.inside-revit#1201]
We did have this component at one time.. https://github.com/mcneel/rhino.inside-revit/pull/335

The host grids is not returning Sloped Glazing Grids.

https://discourse.mcneel.com/t/deconstruct-ceiling/193436

Tested in 

Rhino.Inside Revit: 1.26.9054.19728 (2024-10-15T10:57:36)

[Expanded Information]
Rhino: 8.14.24289.06001 (Rhino 8)
Revit: 2022.1.7 (22.1.70.9)
CLR: 4.0.30319.42000 (4.8.9277.0)

![image](https://github.com/user-attachments/assets/08aab6e4-999c-4631-87b7-2984b66fbbf9)

**Comment by kike-garbo** [comment]
Is working on my side.
![image](https://github.com/user-attachments/assets/61ccc6fc-8b05-4a86-b80c-833becb02d65)

@japhyw Can you attach a .rvt model.

**Comment by japhyw** [comment]
Here is an example in Revit 2023

[host-grids-slopedglazing.zip](https://github.com/user-attachments/files/17524472/host-grids-slopedglazing.zip)
@kike-garbo

**Comment by kike-garbo** [comment]
@japhyw The issue is this Roof is created from a Mass face.
When this happens there is no API to access the CurtainGrids hosted on it.
