### ISSUE TITLE
Add Structural Beam Tracking - Updates does not work

### ISSUE THREAD

**Issue by Jessesn** [mcneel/rhino.inside-revit#1209]
**Versions**

> Rhino.Inside Revit: 1.25.9063.15948 (2024-10-24T08:51:36)
> Rhino: 8.13.24317.13001 (Rhino 8)
> Revit: 2024.3 (24.3.0.13)

Got this feedback from Discourse, https://discourse.mcneel.com/t/structural-beam-tracking-updates-does-not-work/195039

https://github.com/user-attachments/assets/9b83ce19-6d26-4751-acac-0660d3c77e68

[AddStructuralBeamIssue.zip](https://github.com/user-attachments/files/17828567/AddStructuralBeamIssue.zip)

**Comment by kike-garbo** [comment]
Fixed on v1.27
