### ISSUE TITLE
Non-Tag items in Tag.CategoriesPicker

### ISSUE THREAD

**Issue by eirannejad** [mcneel/rhino.inside-revit#121]
**Describe the bug**
Revit API incorrectly marks a series of categories as `Tag` categories. In reality these are annotative components mostly used to construct other annotative components. e.g. Level Heads are used in defining Level Types.

These items should be removed from `Tag.CategoriesPicker` and added to `Annotation.CategoriesPicker` IMHO

![0cHeNK8tCh](https://user-images.githubusercontent.com/8197916/73376976-294ff680-4273-11ea-8198-e0e646f1494c.png)
![e8uNlD4lDl](https://user-images.githubusercontent.com/8197916/73376977-294ff680-4273-11ea-8b82-7491619df4e6.png)

**Comment by kike-garbo** [comment]
![image](https://user-images.githubusercontent.com/3530512/124029321-4ef7a700-d9f5-11eb-8707-57da07e08e6a.png)

![image](https://user-images.githubusercontent.com/3530512/124029230-35eef600-d9f5-11eb-9c22-9aa2a863b3a9.png)
