### ISSUE TITLE
Window does not remember its size and location after picking elements

### ISSUE THREAD

**Issue by eirannejad** [mcneel/rhino.inside-revit#126]
**Describe the bug**
Grasshopper window does not remember its size and location after picking elements. Otherwise the window is displayed at the previous size and location normally.

**BAD**
![WxNMHCKfqb](https://user-images.githubusercontent.com/8197916/73397825-29fb8380-4299-11ea-82ff-9f1c269ff506.gif)

**GOOD**
![Eh6IdWyOZq](https://user-images.githubusercontent.com/8197916/73397926-5d3e1280-4299-11ea-864c-791f614c20dc.gif)

**Comment by kike-garbo** [comment]
It remembers the size and the position if it is not **docked** to the side of the monitor.
