### ISSUE TITLE
GHPython editor stays open, and shortcuts don't work

### ISSUE THREAD

**Issue by eirannejad** [mcneel/rhino.inside-revit#128]
**Describe the bug**
When editing a python compoent in Grasshopper, switching to other windows cause the GH window to hide, but the editor window stays open.

When user comes back to the editor, the keyboard shortcuts (e.g copy, paste) don't work.

[GHPython Editor Stays Open.zip](https://github.com/mcneel/rhino.inside-revit/files/4136270/GHPython.Editor.Stays.Open.zip)

**Comment by kike-garbo** [comment]
Fixed at #173

**Comment by eirannejad** [comment]
Confirmed this has been fixed on the `wip`. Thanks a lot @kike
