### ISSUE TITLE
Editing Family throws error in GH-Python component

### ISSUE THREAD

**Issue by eirannejad** [mcneel/rhino.inside-revit#129]
**Describe the bug**
When attempting to `doc.EditFamily` inside a GH-Python component, GH throws an error. Seems like there is an open transaction on the active document when executing the definition.

![Revit_6BsFEvrNJr](https://user-images.githubusercontent.com/8197916/73491237-013fc080-4363-11ea-8de5-802ae4c1820f.png)

[EditFamily.zip](https://github.com/mcneel/rhino.inside-revit/files/4136285/EditFamily.zip)

**Comment by kike-garbo** [comment]
Related to #132

**Comment by eirannejad** [comment]
#132 is closed so this probably needs to be closed too
