### ISSUE TITLE
Rhino.Inside: Revit - The grasshopper shortcut isn't functional

### ISSUE THREAD

**Issue by samuto** [mcneel/rhino.inside-revit#13]
when activating rhino windows, the shortcut for rhino works well, but when activating grasshopper window, the keyboard is controlling Revit shortcut instead of the grasshopper shortcut.

**Comment by kike-garbo** [comment]
This is fixed in the latest Rhino WIP (7.0.20021.12255, 01/21/2020)
You need to update to that version of Rhino.
