### ISSUE TITLE
Revit.ActiveUIDocument.ActiveView returns null

### ISSUE THREAD

**Issue by eirannejad** [mcneel/rhino.inside-revit#132]
**Describe the bug**
`Revit.ActiveUIDocument.ActiveView` returns null. `Revit.ActiveUIDocument.ActiveGraphicalView` returns correct active graphical view.

## Related To
- https://discourse.mcneel.com/t/rhinowip-new-update-rhinoinside-revit-activedbdocument-activeview-giving-null/95696

**Comment by kike-garbo** [comment]
Fixed using the latest Rhino version.
