### ISSUE TITLE
Wrong Filter Selection on Component Context Menu

### ISSUE THREAD

**Issue by eirannejad** [mcneel/rhino.inside-revit#135]
Components with filter-selectors on the context menu, do not show the correct filter selection when context menu is shown after component is created and the filter is set.

![Revit_a9cAmLKbcg](https://user-images.githubusercontent.com/8197916/73563217-ac0eb800-4411-11ea-8ee0-3f583b66194d.png)

![Q7WNiYt2ry](https://user-images.githubusercontent.com/8197916/73563252-baf56a80-4411-11ea-9672-3153b1ff00a5.gif)

**Comment by kike-garbo** [comment]
Fixed on the latest release.
