### ISSUE TITLE
Zoom in Rhino view

### ISSUE THREAD

**Issue by MingboPeng** [mcneel/rhino.inside-revit#14]
In Rhino window from Revit, all views is not response to mouse middle button zoom control.
Right now, I am using CTRL + right button, and SHIFT + right button as an alternative.

Thanks,
Mingbo

**Comment by eirannejad** [comment]
Please follow these pages and report the issues back to developers
- [Troubleshooting](https://www.rhino3d.com/inside/revit/beta/reference/toubleshooting)
- [Known Issues](https://www.rhino3d.com/inside/revit/beta/reference/known-issues)
