### ISSUE TITLE
Grasshopper window locks in hidden mode and Revit becomes unusable

### ISSUE THREAD

**Issue by eirannejad** [mcneel/rhino.inside-revit#141]
**Describe the bug**
When certain modal windows e.g. Edit Window of a DropDown Component, are open in Grasshopper and user switches to a different application, Grasshopper window alongside the modal window are switched to hidden and there is no way to get them back.

See the video shared here

[Hidden Modal Window.zip](https://github.com/mcneel/rhino.inside-revit/files/4155166/Hidden.Modal.Window.zip)

**Comment by kike-garbo** [comment]
#173 fixes this.
