### ISSUE TITLE
Category picker for DB.CategoryType.Internal

### ISSUE THREAD

**Issue by eirannejad** [mcneel/rhino.inside-revit#142]
Some of the important Revit categories are marked as internal by Revit API but they need to be accessible to users e.g. `Views` cateogry is needed to list the views in a model using the `Element.CategoryFilter`

[Querying View Types](https://www.rhino3d.com/inside/revit/beta/guides/revit-views#querying-view-types) should be done similarly to [Querying Types](https://www.rhino3d.com/inside/revit/beta/guides/revit-types#querying-types)

**Comment by kike-garbo** [comment]
Fixed in 316f5afc87b5d99c0aef187747fd42287c6befdf
