### ISSUE TITLE
Copy Version info to clipboard

### ISSUE THREAD

**Issue by eirannejad** [mcneel/rhino.inside-revit#148]
Allow copying version info to clipboard so users can share their version info on forum and bug reports easier

![troubleshooting-about03](https://user-images.githubusercontent.com/8197916/73973066-bbd94100-48d6-11ea-8128-14b229949593.png)

**Comment by kike-garbo** [comment]
![image](https://user-images.githubusercontent.com/3530512/75674713-fa6bdc80-5c85-11ea-934b-6f8ae87f3778.png)

**Comment by eirannejad** [comment]
Is all this info necessary? Could we shrink think down to just versions of various components?

```
[Window Title]
Rhino.Inside - About

[Main Instruction]
Rhino.Inside© for Revit

[Content]
Rhino.Inside Revit: 0.0.7363.37108 (2/28/2020 8:36:56 PM)

[Expanded Information]
Rhino: 7.0.20056.13055 (Public Build)
Revit: 2019.2 (20190808_0900(x64))
CLR: 4.0.30319.42000 (4.8.03752)
OS: Microsoft Windows NT 10.0.18363.0

[V] See details  [Web site] [Read license] [See source code] [OK]

[Footer]
Press CTRL+C to copy this information to Clipboard
```
