### ISSUE TITLE
Creating new views corrupts the Project Browser

### ISSUE THREAD

**Issue by eirannejad** [mcneel/rhino.inside-revit#149]
**Describe the bug**
Creating new views corrupts the Project Browser. 

![jkXT9pe7la](https://user-images.githubusercontent.com/8197916/74063744-fd84ed00-49a5-11ea-8578-3f539a3f2aea.png)

![q6qjmCtIS8](https://user-images.githubusercontent.com/8197916/74063754-05dd2800-49a6-11ea-9aeb-325d0f30c14b.gif)

See attached GH definition

[Create Views.zip](https://github.com/mcneel/rhino.inside-revit/files/4172838/Create.Views.zip)

**Comment by kike-garbo** [comment]
This is solved in the latest Rhino.
