### ISSUE TITLE
Document components should accept a DB.Document as input

### ISSUE THREAD

**Issue by eirannejad** [mcneel/rhino.inside-revit#151]
**Describe the bug**
Document components should accept a `DB.Document` as input. This is incredibly helpful when working with linked documents.

![Revit_adtHoaF2nn](https://user-images.githubusercontent.com/8197916/74073027-abe85c80-49bd-11ea-8ed9-389409f64385.png)

See [Accessing Linked Document Elements](https://www.rhino3d.com/inside/revit/beta/guides/revit-links#accessing-linked-document-elements) on Wiki

**Comment by kike-garbo** [comment]
Comming...

**Comment by kike-garbo** [comment]
Fixed in #180

**Comment by kike-garbo** [comment]
This issue was related to Document components and now Document components accept a document as an input.
Creation components are a different beast.
I created #183 for creation components.

**Comment by eirannejad** [comment]
Makes sense
