### ISSUE TITLE
Rhino WIP cycles render error on load time

### ISSUE THREAD

**Issue by eirannejad** [mcneel/rhino.inside-revit#153]
**Describe the bug**
Rhino WIP cycles render error on load time

![Revit_3MLwLG9US2](https://user-images.githubusercontent.com/8197916/74290240-19f69180-4ce6-11ea-9a72-220f0d798427.png)

## Related To
- https://discourse.mcneel.com/t/rir-started-with-an-error/94809/6
- https://discourse.mcneel.com/t/rhino-inside-load-error-plugin/95907

**Comment by kike-garbo** [comment]
This will be fixed on the next Rhino WIP release.
