### ISSUE TITLE
Load grasshopper definitions into the toolbar

### ISSUE THREAD

**Issue by eirannejad** [mcneel/rhino.inside-revit#155]
![02](https://user-images.githubusercontent.com/8197916/74293088-9c834f00-4cee-11ea-8296-6706607f7957.png)

Load grasshopper definitions into the toolbar. Definitions can be grouped into bundles

- **Definition:** name.gh
- **Icon:** name.png
- **Tooltip:** tooltip.png

**Comment by kike-garbo** [comment]
Its what Sample4 prototypes.
So pyRevit. 😉

**Comment by eirannejad** [comment]
pyRevit would be an unwanted dependency for companies that want to deploy and use this product only. It also increases the likelihood of conflicts with other addons.

Rhino.Inside.Revit can easily implement a very simple script loader into the Revit UI to help with automation.

**Comment by michaldengusiak** [comment]
great to see it implemented... how can I scroll it to the left? 


![image](https://user-images.githubusercontent.com/26113670/111696603-676bf900-882c-11eb-946d-e09eeff2217e.png)

**Comment by eirannejad** [comment]
Use `-` in the script names to add a new line on the icon name. The buttons will be smaller that way.

Actually! Is this the `Dynamo **` pulldown menu opening? Why is it horizontal?!!! Seems like the panel is so big that is taking the second line ha?

**Comment by michaldengusiak** [comment]
I tried also with space but did not work
![image](https://user-images.githubusercontent.com/26113670/111800040-79e54180-88c3-11eb-8c39-38d3477d46e2.png)
![image](https://user-images.githubusercontent.com/26113670/111800055-7ea9f580-88c3-11eb-9f6a-ac5efe213bef.png)
yes I am using my Dynamo Player folder
![image](https://user-images.githubusercontent.com/26113670/111800170-9d0ff100-88c3-11eb-9bea-862619346691.png)

**Comment by eirannejad** [comment]
@michaldengusiak Woops. I meant `-` (fixed the comment above) Revit UI doesn't like long names so try to avoid that. We'll add more flexibility to this script loader as we go forward to support more features

![Screen Shot 2021-03-19 at 11 02 38 AM](https://user-images.githubusercontent.com/8197916/111823850-accb0d80-88a2-11eb-8b0c-a70ae122f152.png)
![Screen Shot 2021-03-19 at 11 02 28 AM](https://user-images.githubusercontent.com/8197916/111823854-ad63a400-88a2-11eb-81d4-e9e20793960d.png)
![Screen Shot 2021-03-19 at 11 02 23 AM](https://user-images.githubusercontent.com/8197916/111823857-adfc3a80-88a2-11eb-9ce7-4236d3bf26ac.png)

**Comment by michaldengusiak** [comment]
this is perfect but why my icons do not start from left?

![image](https://user-images.githubusercontent.com/26113670/111865106-fed06980-895c-11eb-9ca4-ec20e55c9094.png)


I tried to rename folder... :) color had changed but still the same with icons

![image](https://user-images.githubusercontent.com/26113670/111865308-41df0c80-895e-11eb-9a10-4eecfb3412fc.png)

**Comment by eirannejad** [comment]
Revit pops out the panel because there are too many icons on it that doesn't fit the screen. We'll add support for more button types soon :D Maybe throw them in a folder for now so you'd get a pulldown menu

**Comment by michaldengusiak** [comment]
ok ...today I opened Revit again and looks is the perfect fit ... so 11 scripts :) is correct nr 
![image](https://user-images.githubusercontent.com/26113670/111904990-69f36c00-8a41-11eb-8dfb-76fdb5758253.png)

**Comment by eirannejad** [comment]
😆 11 is a good number!

**Comment by eirannejad** [comment]
Closing this issue since the new ui layout is implemented and is released.

**Comment by dianafox24** [comment]
How can I change the image of the tools shown in the bar? I followed the process by creating a square png image with the same naming as the grasshopper script, but it doesn't seem to change the image of the tool in Revit.
