### ISSUE TITLE
Create Wall From Profile component

### ISSUE THREAD

**Issue by eirannejad** [mcneel/rhino.inside-revit#157]
Create Wall From Profile component

![lKVDkGFKQS](https://user-images.githubusercontent.com/8197916/74371777-44038e80-4d8e-11ea-84a0-f8c5c59b82f0.gif)

[wall from profile.zip](https://github.com/mcneel/rhino.inside-revit/files/4194736/wall.from.profile.zip)

## Related To
- https://discourse.mcneel.com/t/edit-wall-shape/91642/4

**Comment by fSA64** [comment]
Hi, 

Thanks for this amazing component. 
I tried to apply the component on multiple surfaces, but it didn't work. Does it only works for one wall?

Cheers

![TEST 01](https://user-images.githubusercontent.com/68371086/87641676-bcf58080-c748-11ea-997d-234dba038b18.JPG)
![TEST 01b](https://user-images.githubusercontent.com/68371086/87641681-be26ad80-c748-11ea-9683-6bab84065f1d.JPG)

**Comment by attheeast18** [comment]
Hi, are there any updates to this? I have the same problem when creating multiple walls. It would really be helpful if this command can be perfected because we're making so much models.
