### ISSUE TITLE
Components should replace elements by default with an option to modify existing

### ISSUE THREAD

**Issue by eirannejad** [mcneel/rhino.inside-revit#158]
Revit API does not provide full functionality to modify existing geometry and elements. The assumption should be that the components would create new elements when the input data changes. However, an alternative option on components is necessary to allow the user to request modifying the geometry if possible (Currently the Wall.ByCurve component modifies the previously generated wall if the input curve changes)

![Scratch Pad-2](https://user-images.githubusercontent.com/8197916/74372842-37803580-4d90-11ea-8dcc-87ed0e8965e0.jpg)

**Comment by kike-garbo** [comment]
https://discourse.mcneel.com/t/rhino-inside-revit-direct-shape-update-existing-vs-create-new-geometry-after-modification/83561

It seems the general assumption is the other way around, but I like the idea of allowing the user control this.

**Comment by eirannejad** [comment]
The challenge with setting the default to Modify is that for most operations Revit API does not have modification functionality. It expect most objects to be recreated.

**Comment by eirannejad** [comment]
Decided to create separate "Modify" components. "Create" can always replace
