### ISSUE TITLE
Persistent data in GH document should follow the unit settings on the target model

### ISSUE THREAD

**Issue by eirannejad** [mcneel/rhino.inside-revit#161]
Currently, if a value like `-200` is passed to `ParameterSet` component, it is being translated as `-200` FT no matter what the model unit system is. This is obviously only noticable on Metric models.

## Related To
- https://discourse.mcneel.com/t/wall-bycurve-level-constraints/96431

**Comment by kike-garbo** [comment]
I'm not able to reproduce this.

![image](https://user-images.githubusercontent.com/3530512/76011170-6b282880-5f14-11ea-9872-ca53a4a1618a.png)
