### ISSUE TITLE
GH Dropdown components are larger on high-dpi screens

### ISSUE THREAD

**Issue by eirannejad** [mcneel/rhino.inside-revit#162]
This file has been created on a normal display and then opened on a high-def display and the components are overlapping

![Revit_Lf8WglVxLd](https://user-images.githubusercontent.com/8197916/74457118-af0b9e80-4e3c-11ea-9e96-d7001f45ac98.png)

**Comment by kike-garbo** [comment]
Is this happening with a regular Grasshopper Value List param?
If is the case is something should be fixed in Grasshopper.

**Comment by eirannejad** [comment]
Ya only with the Value List

**Comment by eirannejad** [comment]
This needs to be moved to Grasshopper project. Closing here
