### ISSUE TITLE
Rhino window refuses to be closed

### ISSUE THREAD

**Issue by eirannejad** [mcneel/rhino.inside-revit#164]
**Describe the bug**
This happened two times already but have not been able to figure out how to replicate the issue. Will update when I have nailed it down.

![07sYuTyQAq](https://user-images.githubusercontent.com/8197916/74558698-99b77280-4f17-11ea-839a-d75250ae9ff6.gif)

**Comment by kike-garbo** [comment]
Rhino is the middle of a command asking for objects for control point display in the console.
You can cancel the active command pressing ESC, or we can
We may cancel current command when the user closes Rhino.

**Comment by eirannejad** [comment]
Hmm okay. Closing for now until it comes back and I can better test this. Thanks a lot!
