### ISSUE TITLE
Can not get Filled Region types through standard workflow

### ISSUE THREAD

**Issue by eirannejad** [mcneel/rhino.inside-revit#165]
**Describe the bug**
The suggested workflow for getting element types, does not work for Filled Regions.

![Revit_IvGjj8iQ9Y](https://user-images.githubusercontent.com/8197916/74570503-6c77be00-4f31-11ea-82e6-e17e255f4f54.png)

Revit API does not return anything for the query below:
```python
DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_FilledRegion)
```
Filled Region elements are somehow marked as **Detail Items** in Revit. There is `DB.BuiltInCategory.OST_FilledRegion` and a `DB.Category` object that correspond to **Filled Regions** but they don't seem to be used:

![Revit_OmkasiMrcR](https://user-images.githubusercontent.com/8197916/74570486-671a7380-4f31-11ea-82b0-4730b0ab7619.png)

This odd behaviour needs to be wrapped and simplified in RiR for better experience. The filter components should list Filled Region and Filled Region Types, internally, based on classes:

**Filled Regions**
```python
DB.FilteredElementCollector(doc).OfClass(DB.FilledRegion)
```
**Filled Region Types**
```python
DB.FilteredElementCollector(doc).OfClass(DB.FilledRegionType)
```

**Comment by kike-garbo** [comment]
Now that we have 'Element Classes' picker there is a way to pick those elements.

![image](https://user-images.githubusercontent.com/3530512/124028416-3b980c00-d9f4-11eb-9b65-8114938ef515.png)
