### ISSUE TITLE
Renaming a Grasshopper Component causes the focus to switch away from Grasshopper

### ISSUE THREAD

**Issue by clicketyclackety** [mcneel/rhino.inside-revit#179]
**Describe the bug**
Editing the name of a Grasshopper Component and then pressing enter will switch focus away from Grasshopper/Rhino and hide the windows.

**To Reproduce**
1. Open up Grasshopper through Rhino.Inside-Revit
2. Place any Component on the canvas
3. Right click to rename the Component
4. Finish renaming by pressing enter
5. Grasshopper/Rhino should hide

**Expected behavior**
The expected behaviour would be that Grasshopper/Rhino do not hide

**Additional context**
I have found that clicking the canvas instead of pressing enter prevents this.

**Comment by eirannejad** [comment]
A recent feature has been implemented by @kike that allows the Rhino.Inside.Revit windows to be open and not hide anymore so it removes this issue completely.  We are testing it right now so stay tuned for a new build next week.

**Comment by clicketyclackety** [comment]
Thanks @eirannejad!
