### ISSUE TITLE
Sample GH scripts won't run

### ISSUE THREAD

**Issue by nreifenstein** [mcneel/rhino.inside-revit#2]
Some of the sample GH scripts will not run - it appears that assemblies (dll's) are not where they are supposed to be. 

![RhinoInside Revit Sample2 Fail](https://user-images.githubusercontent.com/4603600/67422430-53648f00-f587-11e9-94f7-58c03992730d.png)

**Comment by eirannejad** [comment]
This is a work in progress project. Please see the [samples on the wiki](https://www.rhino3d.com/inside/revit/beta/samples/) for the most current samples.
