### ISSUE TITLE
There's something wrong with Level filter，Logical and filter

### ISSUE THREAD

**Issue by Edisonliu007** [mcneel/rhino.inside-revit#209]
**Describe the bug**
There are two walls, and I use the "Logical and filter"to filter the first wall,
it works when i only use the "categaroy filter",
But it doesn't work when i use the "level filter"and"categaroy filter",i think there's something wrong with the "level filter".
Please help me
![1](https://user-images.githubusercontent.com/63287219/79533913-bbfe7580-80ab-11ea-8c8b-5b4cfcd4b00b.png)
![Uploading 2.png…]()

**Comment by eirannejad** [comment]
Resolved the bug and will be published with the next release https://github.com/mcneel/rhino.inside-revit/commit/03b3291ea4186d017b9f9b204999f364cb970af2

**Comment by Edisonliu007** [comment]
> Resolved the bug and will be published with the next release [03b3291](https://github.com/mcneel/rhino.inside-revit/commit/03b3291ea4186d017b9f9b204999f364cb970af2)

Hi bro. Thank you so much
