### ISSUE TITLE
Rhino.Inside Installer does not copy any of the Revit plugin files

### ISSUE THREAD

**Issue by alexberd** [mcneel/rhino.inside-revit#211]
Attempted to install the latest version of RhinoInside.Revit.msi and after the installation there was no "addin" file copied at the "%appdata%\Autodesk\Revit\Addins\2019" folder.

The problem may be related to the installation path. Installation worked perfectly in a different PC which was not connected to a Windows Server environment.

**Comment by eirannejad** [comment]
Did it copy the addons for other Revit versions?!

**Comment by alexberd** [comment]
I previously managed to install Rhino.Inside without a problem. Currently, I am working in a different computer which has this problem with all Rhino Inside versions. Weirdly installer finishes successfully without giving me any error messages, but none of the files are copied in the Revit plugins path.

**Comment by alexberd** [comment]
The release of this month fixed this issue.
