### ISSUE TITLE
Rhino.Inside Revit - Element - Delete Element

### ISSUE THREAD

**Issue by michaldengusiak** [mcneel/rhino.inside-revit#235]
Would be possible to add true/ false input Toggle to` Delete Element` or make the second node. 
Everyone always forgets to detach this node and this cause issue. With `Button` component this will be the perfect solution. 

![image](https://user-images.githubusercontent.com/26113670/81300467-a0193e80-906f-11ea-80b5-939871bf1780.png)

**Comment by kike-garbo** [comment]
We are working into add a new `Trigger` component.
This new component will be able to expire and recompute any component or group of components.

Meanwhile Grasshopper already provide a component to help into this kind of situations using the `Stream Gate`.

![image](https://user-images.githubusercontent.com/3530512/83948242-392ca800-a81c-11ea-97b3-60bf5a90ae7c.png)
