### ISSUE TITLE
Rhino.Inside.Revit remember selected values

### ISSUE THREAD

**Issue by michaldengusiak** [mcneel/rhino.inside-revit#236]
after opening GH script ie. `category `does not store selection value, is. I have `Levels `and when open again need to select again `Levels`
![image](https://user-images.githubusercontent.com/26113670/81304456-fc329180-9074-11ea-81bb-b8a4c71937cd.png)

**Comment by kike-garbo** [comment]
Keep in mind that all Rhino.Inside parameter nodes reference Elements, Types, Levels and Categories per document. This allows us to reference elements in multiple documents from the same Grasshopper definition.
This means that when the user reference the 'Level 1' in the document 'Project 1' is referencing this level in this document.

![image](https://user-images.githubusercontent.com/3530512/83948532-24511400-a81e-11ea-9b31-3c7a69306e8d.png)

If you use the same Grasshopper definition that is referencing 'Level 1' in 'Project 1' on the 'Project 2' it will show you that warning.

![image](https://user-images.githubusercontent.com/3530512/83948579-798d2580-a81e-11ea-90bf-08e45001dd8f.png)

If you want to reference Levels by name you can use the 'Document Levels' component like this.

![image](https://user-images.githubusercontent.com/3530512/83948705-3b443600-a81f-11ea-9f56-89a1cffe297b.png)
