### ISSUE TITLE
"Document Walls"-component doesn't grap all walls in document.

### ISSUE THREAD

**Issue by Hermasetas** [mcneel/rhino.inside-revit#259]
The walls not being grabbed are attached to masses in revit.

![image](https://user-images.githubusercontent.com/41925281/83006194-2216da80-a012-11ea-8a4f-952ca1fafe82.png)

**Comment by eirannejad** [comment]
"Wall Types" component has been deprecated

**Comment by Hermasetas** [comment]
> "Wall Types" component has been deprecated

I'm not sure how this addresses the problem.. The issue was with the "Document walls" component.

**Comment by eirannejad** [comment]
Since the component does not exist, the component, the alternative method does not have that issue:

![Screen Shot 2020-07-10 at 09 00 36](https://user-images.githubusercontent.com/8197916/87174322-d8194980-c28b-11ea-84d4-d5d87a189cf0.png)
