### ISSUE TITLE
"Analyze wall"-component returns width in feet instead of millimeters.

### ISSUE THREAD

**Issue by Hermasetas** [mcneel/rhino.inside-revit#263]
![image](https://user-images.githubusercontent.com/41925281/83117145-01f82180-a0cd-11ea-832b-65578df9d310.png)

**Comment by eirannejad** [comment]
Fixed https://github.com/mcneel/rhino.inside-revit/commit/3a734e3c0ea502e83854a10482ff23207eebc354
