### ISSUE TITLE
Category picker is missing builtin sub-categories

### ISSUE THREAD

**Issue by eirannejad** [mcneel/rhino.inside-revit#294]
**Describe the bug**
All the built-in categories are represented in Revit API by the DB.BuiltInCategory enum but this is missing the built-in subcategories like `Wall Sweeps`. The function that extracts categories from a model, needs to include the subcategories as well so the components that rely on a category getter, receive all the available categories:

```python
def get_doc_categories():
    all_cats = []
    # document categories
    cats = doc.Settings.Categories
    all_cats.extend(cats)
    # subcategories for each category
    for cat in cats:
        all_cats.extend([x for x in cat.SubCategories])
    return all_cats
```

**Comment by kike-garbo** [comment]
What do you mean by the Category Picker?
1. ![image](https://user-images.githubusercontent.com/3530512/87717517-cc101900-c7b0-11ea-9a5f-80306d659f9d.png)
2. ![image](https://user-images.githubusercontent.com/3530512/87717432-a84cd300-c7b0-11ea-8138-e3ac87fa962b.png)

None of them suport sub-category picking.

Now we have the `Category SubCategories` component that returns all the sub-categories of a category.
![image](https://user-images.githubusercontent.com/3530512/87717181-4e4c0d80-c7b0-11ea-8479-1f9ca2d0a19b.png)

**Comment by IMVVVVVIP** [comment]
#309

**Comment by kike-garbo** [comment]
![image](https://user-images.githubusercontent.com/3530512/124028987-ef010080-d9f4-11eb-9e67-ca9160ade070.png)
