### ISSUE TITLE
Missing Components? 

### ISSUE THREAD

**Issue by like7171** [mcneel/rhino.inside-revit#295]
**Describe the bug**
I am new to Rhino Inside. I realized that there are some missing components in Grasshopper. 
I am using Revit 2019 and Rhino 7 WIP with a valid Rhino 6 account. 
I opened Rhino and Grassshopper in Revit. The Revit components in Grasshopper, the layout of components are somewhat diffferent and I can't even find some of components that every people in tutorials using. (e.g Document Categories Component)

![23](https://user-images.githubusercontent.com/68126423/87192445-4e797400-c2ab-11ea-9150-1a577ffc9482.png)

![123](https://user-images.githubusercontent.com/68126423/87192378-3144a580-c2ab-11ea-8ba7-8f3bdae3a5b4.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by kike-garbo** [comment]
Hi,

This component has been renamed to 'Query Categories', and is under the Category panel.
