### ISSUE TITLE
cannot view source of C# and VB script components 

### ISSUE THREAD

**Issue by kaiaurelienzhu** [mcneel/rhino.inside-revit#296]
**Describe the bug**
It is not possible to open a C# or VB script component text editor when running rhino inside revit grasshopper. 

**To Reproduce**
1. Place a C# or VB script component on the grasshopper inside revit canvas.
2. Double click on the component or right click component and select "Edit Source"
3. You should see the small icon pop up for a fraction of a second then it disappears. 
4. Nothing more happens, when you try and double click again, nothing appears.

**Expected behavior**
I expected to be able to double click on the C# component or right click and select "Edit source" and be able to see the text editor pop up for me to view and edit the code inside. 

**Additional context**
I am testing using Revit 2020.1 with latest rhino WIP and RiR builds.
The bug only occurs when running from within a revit instance. Tested on both Rhino6 and Rhino WIP (outside of Revit) with no issues.
Python script component had no issues and opened with no issues.

**Comment by kike-garbo** [comment]
Hi @kaiaurelienzhu,

We just released a major update to Rhino.Inside.Revit.
This build attempts to resolve conflict errors like the one you are descriving here.
It would be great if you could download and install this new version to see if it solves all the load problems.

Thanks,

**Comment by kaiaurelienzhu** [comment]
@kike-garbo, I have tested with latest and it all works, issue resolved.

Many thanks,
