### ISSUE TITLE
What do you mean by the Category Picker?

### ISSUE THREAD

**Issue by IMVVVVVIP** [mcneel/rhino.inside-revit#310]
What do you mean by the Category Picker?
1. ![image](https://user-images.githubusercontent.com/3530512/87717517-cc101900-c7b0-11ea-9a5f-80306d659f9d.png)
2. ![image](https://user-images.githubusercontent.com/3530512/87717432-a84cd300-c7b0-11ea-8138-e3ac87fa962b.png)

None of them suport sub-category picking.

Now we have the `Category SubCategories` component that returns all the sub-categories of a category.
![image](https://user-images.githubusercontent.com/3530512/87717181-4e4c0d80-c7b0-11ea-8479-1f9ca2d0a19b.png)

_Originally posted by @kike-garbo in https://github.com/mcneel/rhino.inside-revit/issues/294#issuecomment-659645226_

**Comment by eirannejad** [comment]
Not an issue
