### ISSUE TITLE
Load Rhino.Inside.dll and RhinoCommon.dll programatically

### ISSUE THREAD

**Issue by ThomasMahon** [mcneel/rhino.inside-revit#311]
**Is your feature request related to a problem? Please describe.**
Unable to run Revit add-in with dependencies on Rhino.Inside.dll and RhinoCommon.dll until Add-Ins > Rhino button is manually clicked on the Revit toolbar. 

This also applies with Dynamo custom nodes which make calls to either library. 

**Describe the solution you'd like**
We need to be able to load the Rhino.Inside.dll and RhinoCommon.dll when our Revit add-in is launched without needing to launch Rhino Inside (via Add-Ins > Rhino button click) first. This is a major blocker as our app wont work until RhinoInside is running and its an inconvenience/nuisance to have to inform the user that they need to click on the Rhino button first before running our app - in most cases the most intuitive behaviour the user has is to simply click our button to run our app but this will result in exceptions if Rhino.Inside isn't running as we are blocked from accessing RhinoCommon. 

**Describe alternatives you've considered**
1. Using the PostCommand to initiate the button click however this loads all the other dll's for Rhino.Inside which we dont need and this is too slow - the user is waiting up to 15 seconds just to load Rhino.Inside before our app can even launch. 

2. Check if the dlls are loaded and if not show a warning to the user that they need to click the Add-Ins > Rhino button first then re-run our app. This isn't really something we would consider as it creates a bad user experience and is simply a nuisance. 

We just want to be able to access the 2 libraries and don't need nor want the overhead of loading the Rhino toolbar every time our app is run. 

Is there a way to load these two dll's only and can we achieve it when our app initialises?

**Comment by kike-garbo** [comment]
Hi,

The 15 seconds you mention is the time Rhino takes to load.
RhinoCommon.dll is only the Rhino .NET API, but the real implementation is in Rhino, that needs to be fully loaded before calling to it.

As you already considered the best way right now is using a PostCommand to force a full load.

```C#
static class RhinoInsideAddin
{
  static readonly string CommandName = @"CustomCtrl_%CustomCtrl_%Add-Ins%Rhinoceros%CommandRhinoInside";
  public static bool IsInstalled = !(RevitCommandId.LookupCommandId(CommandName) is null);
  public static void Load()
  {
    if(RevitCommandId.LookupCommandId(CommandName) is RevitCommandId commandId)
      Revit.ActiveUIApplication.PostCommand(commandId);
  }
}
```

We can try to figure out a way to not load the ribbon buttons, but this will have no impact on the load time.

**Comment by ThomasMahon** [comment]
Hi Kike

Great, thanks for confirming the best way forwards for now - since PostableCommand is asynchronous we are going to map this to a button the Revit ribbon and have it enable the buttons which launch our app after in a 2-step process. 

If its possible to request an enhancement so it is possible to load Rhino.Inside using an API call that would be greatly appreciated and really help to streamline our integrations.

**Comment by kike-garbo** [comment]
Hi @ThomasMahon,
Do you mind if we keep this open to follow this issue?
I'm with you that a synchronous implementation is desirable.

**Comment by ThomasMahon** [comment]
Hi @kike-garbo sure no problem 👍

**Comment by kike-garbo** [comment]
Now first access to 'RhinoCommon.dll' loads Rhino.
see 9bd33e6ea513ab528918c2ce2417acc77b5a79ff

**Comment by ThomasMahon** [comment]
@kike-garbo I've followed your comment above verbatim; my Revit app simply loads and makes a call to RhinoCommon. However it doesn't load RhinoCommon so I get an exception instead. I'm not distributing any of the Rhino dlls in my app (i.e. they are no being loaded by my apps root install location). 

Can you explain what I should be doing? 

![image](https://user-images.githubusercontent.com/18601851/164182823-1aa6b433-992e-40fc-a081-392ccbdd843b.png)

If I include RhinoCommon in my app root, then I get this exception:
![image](https://user-images.githubusercontent.com/18601851/164183730-55cad8f3-19d3-4037-90ab-5a34bc055fb3.png)

I'm running:
Rhino 7.16.22067.13001, 2022-03-08
RiR 1.3.7983.15227

**Comment by ThomasMahon** [comment]
Hi @kike-garbo can you give me any direction on this?

**Comment by kike-garbo** [comment]
This was implemeted on v1.6
