### ISSUE TITLE
Search Families by using *Askerisk*

### ISSUE THREAD

**Issue by alexberd** [mcneel/rhino.inside-revit#312]
Is there any way to search and filter family types by using an asterisk (*) ? I am looking a way to find all family types which contain the word "Steel".

![image](https://user-images.githubusercontent.com/4086522/89517819-30cbfb80-d7d2-11ea-9152-57cfef148c29.png)

Probably this is already resolved but I couldn't find any information online so I post it here.

Many thanks,

**Comment by kike-garbo** [comment]
You are right there is no documentation about this.
We support several query syntax depending on the first character of the mask.
Here some samples.

![image](https://user-images.githubusercontent.com/3530512/89578138-01e57200-d832-11ea-8d7d-f644f8dcab20.png)
