### ISSUE TITLE
Implement Assembly Resolver for using third party DLLs without issues

### ISSUE THREAD

**Issue by kristoffer-tungland** [mcneel/rhino.inside-revit#320]
Grasshopper has issues loading its components due to a assembly conflict with a Revit addin made by me and some colleges. We have resolved issues like this for other addins by defining a assembly resolver for our addin.

I think if you also implement this you can use a different version of a third party DLL.

Reference for Assembly Resolver
[https://forums.autodesk.com/t5/revit-api-forum/proper-way-to-handle-app-config-bindingredirects-in-revit-add-in/m-p/5693192#M10560](https://forums.autodesk.com/t5/revit-api-forum/proper-way-to-handle-app-config-bindingredirects-in-revit-add-in/m-p/5693192#M10560)

**Comment by kike-garbo** [comment]
Hi Kristoffer,

I agree with your suggestion.
I add this to the top priority things to do.

If you can provide us a simple .gha that fails with the current implementation to test would be amazing.
Thanks.

**Comment by kike-garbo** [comment]
#370 implements this.
