### ISSUE TITLE
GH Active Document node throws exception if its file is closed in the same Revit session.

### ISSUE THREAD

**Issue by ThomasMahon** [mcneel/rhino.inside-revit#324]
**Describe the bug**
If the GH active document node is used and the file is closed the node throws an exception

**To Reproduce**
1. Place an Active Document node on the graph with a Revit file open.
2. Close said file via 'R' button > Close (not the application).
3. Exception thrown as the document is null. This is quite obstructive as the exception is thrown by any other node (or method call I  am making in a C# node) which requires the document object. So I have to continuously close this dialog only for it to display again and again. 
![image](https://user-images.githubusercontent.com/18601851/92931594-964b8180-f43b-11ea-94e8-8979d6a5a057.png)

**Expected behavior**
A more elegant warning? Maybe just the node turning red would be sufficient
![image](https://user-images.githubusercontent.com/18601851/92931901-1245c980-f43c-11ea-8901-c126b8e79d97.png)

or (best option IMO)

Have it automatically attach to the active file (or next active file) so it updates and always does what it says on the node...return the active document.

**Comment by kike-garbo** [comment]
Hey Thomas,

I'm trying to reproduce what you describe with this simple definition without success.

![image](https://user-images.githubusercontent.com/3530512/92994462-9fe7ee80-f4fa-11ea-9967-45f23c2cf0c2.png)

Do you have more components into your definition?

**Comment by ThomasMahon** [comment]
Hi @kike-garbo 

It looks like its a false alarm - the Document node does indeed do what I was expecting it to. I managed to narrow it down to a problem with one of the classes from my own library I am instantiating inside the C# node. This relies on the document object and when switching files the problem emanated from indexing a list out of range (which was valid when run on a previous model).

I'll close this issue as its not a problem with RIR.
