### ISSUE TITLE
Starting Dynamo before RiR causes RiR launch failure

### ISSUE THREAD

**Issue by ThomasMahon** [mcneel/rhino.inside-revit#334]
**Describe the bug**
If Dynamo is launched in Revit before RiR is started, it fails to load correctly and shows the following warning. The Rhino toolbar loads, but its not stable:
![image](https://user-images.githubusercontent.com/18601851/95072919-e7c9f200-0703-11eb-99f4-2ccdd875cd82.png)

For example, if GH is subsequently loaded, none of the Revit nodes are loaded, plus our Revit add-in fails as we have a dependency on RiR but cant make calls to the RiR.dll. 
![image](https://user-images.githubusercontent.com/18601851/95072285-ddf3bf00-0702-11eb-89aa-8fbcc0d16685.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Revit 2019.
2. Manage tab > Dynamo (v2.0+)
3. Close Dynamo after it launches.
4. Click on RiR button to launch.

Warning displays. 

**Expected behavior**
No warnings and loads RiR regardless of whether Dynamo was opened first or not.

**Additional information:**
We encountered a similar issue when we first started implement RiR in our Revit app; if the RiR or RhinoCommon dll's were included in our app root folder (which the manifest points to) these dlls are automatically loaded when our app first runs. This would fail as Rhino needs to be running before we can make calls to RhinoCommon. If the RiR button was clicked after this has happened, RiR would fail to load correctly with similar warning messages to the one shown above, so the issue was loading dlls RiR has dependencies on before it is able to load them.

I've done the checks to rule out if its anything our app is doing. The Rhino dlls are not in any custom node package in Dynamo or our root install folder. 

Perhaps its another dependency? 

**Versions**
Revit 2019.2
Dynamo 2.0.2
R7 7.0.20259.15365
RiR 0.0.7557.14292

**Comment by scotttd** [comment]
I know in 2019, Dynamo loads a Python library that is old enough to limit standard ironpython libraries to be loaded.  I expect everything you test will load in 2020 or above?  And that if RIR is loaded first everything loads?

**Comment by ThomasMahon** [comment]
Hi @scotttd 

Same issue in 2020 but that's probably because Dynamo v2.3 (the one shipped with 2020) still uses the old IronPython which v2.0.2 is using.

**Comment by ThomasMahon** [comment]
It might be worth adding this to the release notes in RiR if this conflict is unresolvable as a lot of organisations are still using R2019 and are more likely to upgrade to 2020 next year which still has the problem if my tests are correct.

**Comment by kike-garbo** [comment]
Hi,

We just released a major update to Rhino.Inside.Revit.
This build attempts to resolve the loading and runtime errors you have experienced.
It would be great if you could download and install this new version to see if it solves all the load problems.

Thanks,

**Comment by ThomasMahon** [comment]
@kike-garbo thanks we'll test from today and I'll let you know if there are any other issues.

**Comment by kike-garbo** [comment]
Hi @ThomasMahon,

Do you mind if we close this issue? On my tests it works well.
If we found other problems we can open other issues.

**Comment by ThomasMahon** [comment]
Hi @kike-garbo sure I also haven't found any issues yet and we've been continually testing with our latest app for the past week. If i notice any other issue we can re-open.
