### ISSUE TITLE
Wall By Profile does not always produce Wall

### ISSUE THREAD

**Issue by scotttd** [mcneel/rhino.inside-revit#337]
**Describe the bug**
There is a marked curve in the 3dm model.  It creates a wall until until dragged down close to the ground level, then it fails as a wall profile.

**To Reproduce**
1. Grab the marks curve and drag it staight down.

**Expected behavior**
I would expect it to always create a wall

[Wall Profile.zip](https://github.com/mcneel/rhino.inside-revit/files/5478246/Wall.Profile.zip)

**Comment by kike-garbo** [comment]
I'm no able to reproduce it.
Please save the curve in the failing position.

![image](https://user-images.githubusercontent.com/3530512/98129422-665bb000-1eb9-11eb-9fb0-3031ddc2b475.png)

**Comment by kike-garbo** [comment]
@scotttd Please test again with the 1.1 and close this issue if fixed.
