### ISSUE TITLE
Rhino Inside Revit Installation Failure

### ISSUE THREAD

**Issue by alexberd** [mcneel/rhino.inside-revit#359]
Rhino Inside Revit today's version installation is showing the following window asking for a path. Not sure what to select here.

Anything I tried didn't work. Any help will be much appreciated. 

![image](https://user-images.githubusercontent.com/4086522/101518779-49b00d80-397a-11eb-87f1-9f9e7d87f97d.png)
![image](https://user-images.githubusercontent.com/4086522/101519046-9a276b00-397a-11eb-8b61-de1556472799.png)

If I press cancel the following installation error appears.
![image](https://user-images.githubusercontent.com/4086522/101519107-aca1a480-397a-11eb-9cb6-22c98470b3ab.png)

**Comment by eirannejad** [comment]
Seems to be resolved
