### ISSUE TITLE
Wish: Set Parameter in GH for Revit

### ISSUE THREAD

**Issue by josols** [mcneel/rhino.inside-revit#36]
It would be really good if a node for setting parameters in Revit existed based on element, parameter name and value.

**Comment by BTorrinha** [comment]
Hello everybody.

I am new here at GH as well as using Rhino Inside, yet I have a bit of experience using Dynamo inside Revit.
While using Dynamo to fill in parameters from some of the geometry inside a family file, one could associate type parameters to other existing parameters in the file.
I would like to know if this would also be possible to be done using Rhino Inside (Grasshopper) and if I could even create family parameters in case they do not exist yet within the file?

Thank you for the amazing work you have been developing.

**Comment by 2adicted** [comment]
Hi,

Has the 'ParameterSet' location changed as well in the recent update? I cannot find it under Element any longer.
