### ISSUE TITLE
Flip element error

### ISSUE THREAD

**Issue by moonyoung14** [mcneel/rhino.inside-revit#360]
After placing family instance (generated in Revit), I would like to flip hand in Rhino inside gh.
Even thou the family planned to be flippable I couldn't find any parameter for this  in the parameter key list..
and it occurs error when I using the "flip element" component.

<img width="511" alt="Capture" src="https://user-images.githubusercontent.com/32700176/101557717-d7611c80-39bd-11eb-9364-5245f685c7bf.PNG">

**Comment by kike-garbo** [comment]
Could you please share what error message is there in the red ballon?

**Comment by moonyoung14** [comment]
> 
> 
> Could you please share what error message is there in the red ballon?

![image](https://user-images.githubusercontent.com/32700176/101644255-43cb3280-3a35-11eb-93a3-7625f932c83c.png)

**Comment by kike-garbo** [comment]
Not all Revit elements support all kinds of flip.

Your family instance elements, for example, need to be authored with this feature.
See an example [here](https://forums.autodesk.com/t5/revit-architecture-forum/how-to-add-flip-facing-hand-to-door-family/td-p/7280940).
