### ISSUE TITLE
Add Bracing Component

### ISSUE THREAD

**Issue by eirannejad** [mcneel/rhino.inside-revit#363]
Similar to Add Beam, except with [StructuralType.Brace](https://apidocs.co/apps/revit/2020/0a0a3793-5fce-283d-4953-a137f5593db9.htm)

```C#
doc.Create.NewFamilyInstance
        (
          centerLine,
          type.Value,
          level.Value,
          DB.Structure.StructuralType.Brace
        );
```
And maybe add components for other types as well or create "Add Framing" and expose this as a parameter

## RE:
- https://discourse.mcneel.com/t/creating-brace-with-rhino-inside-revit/113820

**Comment by kike-garbo** [comment]
Implemented on 5e501e108fca37a445754b229f401b75a96aeff3
