### ISSUE TITLE
This Rhino to Revit Box uses the SAT transfer and not the native transfer

### ISSUE THREAD

**Issue by scotttd** [mcneel/rhino.inside-revit#369]
**Describe the bug**
The single box here should transfer fast to Revit using the standard internal transfer, but instead it is using the SAT transfer method.  In fact all the objects in this model use the SAT method.

[201221 RIR Issue SAT transfer.zip](https://github.com/mcneel/rhino.inside-revit/files/5737159/201221.RIR.Issue.SAT.transfer.zip)

**To Reproduce**
1. Open Revit to a blank model
2. Open the 3DM in Rhino Inside
3. Open the GH definition in Grasshopper'
4. SElect the box with the Geometry Param and see that is makes an SAT.

**Expected behavior**
THis should transfer without making and SAT.

**Customer Thread**
This is the thread this was discovered on. 
https://discourse.mcneel.com/t/directshape-slow-weird-behavior-in-latest-release/114812/4

**Additional context**

**Comment by kike-garbo** [comment]
Current version still go SAT for this geometry but now shows why.

Is the kind of geometry that can be transferred after:
* `Explode`
* `RebuildEdges` to something below 0.005 feet as tolerance.
* `Join` again
* Sometimes `Join` introduces short-edges, but current version is able to handle those edges.

> Rhino document tolerance should be something below 0.005 feet to make this trick work.

![image](https://user-images.githubusercontent.com/3530512/104955324-5b99bd00-59ca-11eb-967f-108a6571ea30.png)
