### ISSUE TITLE
Closed Brep DirectShape Error

### ISSUE THREAD

**Issue by sugimurat** [mcneel/rhino.inside-revit#382]
When I try to create a BREP DirectShape, GH freezes. 
Any suggestions are appreciated. Many thanks. 
![sample01](https://user-images.githubusercontent.com/58685595/105825584-1b0df500-6003-11eb-90a3-450c0af38ea9.jpg)

[20210126_open_issue_sample.zip](https://github.com/mcneel/rhino.inside/files/5871253/20210126_open_issue_sample.zip)

**Comment by bits2atoms** [comment]
Have you tried a simple box ? I have had issues previously when transferring open, non-manifold breps

**Comment by kike-garbo** [comment]
Fixed in 1.2
