### ISSUE TITLE
Rhino.Inside Installation is not copying the Revit Addins 

### ISSUE THREAD

**Issue by alexberd** [mcneel/rhino.inside-revit#386]
The January version of Rhino.Inside is not copying any of the Revit addin files at the profile folders below.

%apdata%\AppData\Roaming\Autodesk\Revit\Addins

This issue may not occur when profiles are not separately set in a server environment.

**Comment by kike-garbo** [comment]
Hi,

Last installer was update to instal Rhino.Inside only with admin rights.
This means now addin files are installed at `%ProgramData%\Autodesk\Revit\Addins`

**Comment by alexberd** [comment]
I confirm that yes, installation does copy the files into the %ProgramData%\Autodesk\Revit\Addins folder.
The problem occurs if a previous Rhino.Inside version was installed at %apdata%\AppData\Roaming\Autodesk\Revit\Addins. Then, the old version overrides the new. To get this fixed you need to delete the old Rhino.Inside version  at the %apdata%\AppData\Roaming\Autodesk\Revit\Addins folder.
