### ISSUE TITLE
Set Parameter fails when setting materials

### ISSUE THREAD

**Issue by eirannejad** [mcneel/rhino.inside-revit#388]
Example files are attached

![Screen Shot 2021-02-15 at 2 20 52 PM](https://user-images.githubusercontent.com/8197916/107998009-05a04100-6f99-11eb-9a64-1802f75b4f07.png)

![Screen Shot 2021-02-15 at 2 19 14 PM](https://user-images.githubusercontent.com/8197916/107997912-ceca2b00-6f98-11eb-817d-085af08ca855.png)

[Files.zip](https://github.com/mcneel/rhino.inside-revit/files/5984364/Files.zip)

**Comment by michaldengusiak** [comment]
I have similar with Space level
https://discourse.mcneel.com/t/how-to-set-upper-limit-for-spaces-issue-with-set-element-parameter/118844

**Comment by eirannejad** [comment]
Fixed and will be published with next release. It is also available in the Daily update channel
