### ISSUE TITLE
GH does not allow to click

### ISSUE THREAD

**Issue by michaldengusiak** [mcneel/rhino.inside-revit#396]
**Describe the bug**
when we send some elements to Revit using RhinoInside and there is some error in Revit I have to go to Revit and click OK.
When I can back to GH can not click anywhere ...I can place nodel but unable to clicl

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/26113670/112285758-8f22ed00-8c82-11eb-8b56-5734fe9ccf61.png)

**Additional context**

**Comment by kike-garbo** [comment]
Can you share a Grasshopper file that reproduces the error please?
