### ISSUE TITLE
Cannot Run Rhino.Inside.Revit after Installation

### ISSUE THREAD

**Issue by deathlordviper** [mcneel/rhino.inside-revit#4]
![image](https://user-images.githubusercontent.com/56639780/66978195-02055d00-f0ba-11e9-8029-893878502b29.png)

Hi Folks I just heard about the Rhino 7 WIP wanted to test it but I get this error msg after running.
I am using Revit 2018.

**Comment by eirannejad** [comment]
Please follow these pages and report the issues back to developers
- [Troubleshooting](https://www.rhino3d.com/inside/revit/beta/reference/toubleshooting)
- [Known Issues](https://www.rhino3d.com/inside/revit/beta/reference/known-issues)
