### ISSUE TITLE
Delete key does not work in Rhino inside Revit

### ISSUE THREAD

**Issue by scotttd** [mcneel/rhino.inside-revit#41]
Here is what is working and not:

1. Open Rhino in Revit
    1. Select Object, Delete Key does **not** work in Rhino.
    1. Copy and Paste using CTRL-C and CTRL-V do work
1. Open Grasshopper in Rhino in Revit
    1. Select component, Delete Key may work Grasshopper.  Some have reported it does not.
    1. Copy and Pate may work in CTRL-C and CTRL-V work. Some have reported it working and some have not.

Anyone else experiencing this?

**Comment by eirannejad** [comment]
It's a know issue. Revit captures all the keystrokes on non-modal windows e.g. none of the standard cut/copy/paste keyboard shortcuts work in pyRevit output window.

 I need to look deeper in to this.

**Comment by scotttd** [comment]
That means the only options is to hook the keyboard ourselves.  Hmm, that will be some work....

**Comment by kike-garbo** [comment]
Is same issue as #13 

I was able to reproduce it here only using a 2019 version, in Revit 2019.2 this is fixed.
DEL key in Rhino window fails in all versions.

**Comment by kike-garbo** [comment]
This is fixed in the latest Rhino WIP (7.0.20021.12255, 01/21/2020)
You need to update to that version of Rhino.
