### ISSUE TITLE
Element Tracker Does Not Highlight Elements in Active Document

### ISSUE THREAD

**Issue by eirannejad** [mcneel/rhino.inside-revit#415]
A series of elements is created using the same component on two different documents. When deleting the GH component, the generated elements are activated in the original document instead of the active one

- Noticed this behaviour with "Add Walls" component but have not tested the other "Add" components
- Example GH definition is attached below

https://user-images.githubusercontent.com/8197916/124999900-f8492900-e003-11eb-9450-f3ca05bacac9.mp4

[Make Walls.gh.zip](https://github.com/mcneel/rhino.inside-revit/files/6787677/Make.Walls.gh.zip)

**Comment by kike-garbo** [comment]
Since the component is working with the Current Document only, the bug was it created geometry on one document without deleteing the previous on the other one.

![image](https://user-images.githubusercontent.com/3530512/125818108-179c3dde-9dd9-4783-9c1f-57369ce4ccdd.png)
