### ISSUE TITLE
Add Model Group component does not place groups at correct level

### ISSUE THREAD

**Issue by eirannejad** [mcneel/rhino.inside-revit#417]
**Add Model Group** component does not place groups at correct level and seems to be following the Z value of the Location point. 

**Larger Design Discussion:** I'd highly suggest to abstract the concept of Location and provide specific GH Parameter for a Level Location, Sheet Location, 3d Location, etc so all similar components can take one "Location" input parameter encapsulating the necessary data (Level, or Sheet reference)

https://user-images.githubusercontent.com/8197916/125000743-ecf6fd00-e005-11eb-9cfa-e1f5793a44ea.mp4

[Place Groups.gh.zip](https://github.com/mcneel/rhino.inside-revit/files/6787706/Place.Groups.gh.zip)

**Comment by kike-garbo** [comment]
You are passing all the points at elevation 0.0.
Levels are correctly assigned and "Origin Level Offset" adjusted acordingly.

![image](https://user-images.githubusercontent.com/3530512/125466974-e9648e52-3642-48fa-b008-7923dd9ad2f1.png)

**Comment by eirannejad** [comment]
The current behaviour doesn't make sense to me. The concepts of Z coordinate and Level are in conflict. Z must be the vertical offset from Level when level is specified.
