### ISSUE TITLE
Always show details of elements being deleted

### ISSUE THREAD

**Issue by eirannejad** [mcneel/rhino.inside-revit#418]
Let's always show this info. It's useful and doesn't take too much UI space

![explorer_cOAs6WmfY0](https://user-images.githubusercontent.com/8197916/125001092-ba013900-e006-11eb-8239-02446f6e7161.png)

**Comment by kike-garbo** [comment]
Now we use the Revit warning error dialog that show more info.

![image](https://user-images.githubusercontent.com/3530512/125459963-3dba1b2b-8dbd-426d-853f-15ceacbf4959.png)
