### ISSUE TITLE
DB.Wall-aware GH nodes to decompose structure and layers

### ISSUE THREAD

**Issue by eirannejad** [mcneel/rhino.inside-revit#42]
Need a few nodes to decompose info about wall structure and contained layers

![wall struct layers](https://user-images.githubusercontent.com/8197916/68327680-a60f7200-0082-11ea-86aa-ba0fb319ea0c.png)

Example files:
[wall structure.zip](https://github.com/mcneel/rhino.inside-revit/files/3816178/wall.structure.zip)

**Comment by kike-garbo** [comment]
Last release contains nodes to achieve this kind of workflows.
