### ISSUE TITLE
Digitally Sign installer and add-on

### ISSUE THREAD

**Issue by golsby** [mcneel/rhino.inside-revit#424]
To trust that Rhino.Inside Revit is coming from us, all our code should be digitally signed - from the add-on itself, to the DLLs it uses, to the installer that distributes it.

McNeel has code signing certificates already, and they can be used here (provided that they are not exposed in the source code).

Requested by Nate Miller at Proving Ground:
![image](https://user-images.githubusercontent.com/521547/126400834-79b17e28-f3f0-4cce-af50-2ef11eb0c2c4.png)

**Comment by pearswj** [comment]
We already digitally sign the DLLs and the installer, but the build step wasn't updated for the 2022 add-on. I've updated it to sign all .dll and .gha files.

```ps1
Get-ChildItem -recurse -path .\src\RhinoInside.Revit*\bin\x64\Release* -Include *.dll,*.gha | % {
  # call signtool on $_.FullName
}
```

**Comment by pearswj** [comment]
@eirannejad, assigning to you to check that everything is signed in the latest daily build

**Comment by eirannejad** [comment]
Built a new build and confirmed 2022 dlls are signed as well. Thanks a lot @pearswj
