### ISSUE TITLE
Implement merge down automatic process

### ISSUE THREAD

**Issue by sbaer** [mcneel/rhino.inside-revit#425]
We need to implement the McNeel merge down process to merge 1.0 changes to 1.x

**Comment by pearswj** [comment]
This uses a custom GitHub Action – https://github.com/mcneel/merge-down-action

The merge-down workflow is triggered when a pull request closes and will skip if the pull request wasn't actually merged.

The custom merge-down action performs the following tasks...

1. If the pull request that just closed was a merge-down, delete the `*-merge-xxx` branch
2. Determine the next (target) branch in the merge-down flow, for example...
    * If the pull request was merged into `1.0`, the next branch will be `1.x`
    * If the pull request was merged into `1.x`, the next branch will be `2.x`
3. Check to see if the target branch exists and exit early if it doesn't
4. Create a new branch from the pull request's head branch and append the `-merge-<target>` suffix
5. Attempt to merge the target branch into the new branch. If this fails it means that there are merge conflicts that require manual intervention.
6. Create a new pull request to merge the new branch into the target branch
7. Enable [auto-merge](https://docs.github.com/en/github/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request), _unless step 5. failed_
8. Assign the new pull request to the author of the original pull request

The process also relies on having [required checks](https://github.com/mcneel/rhino.inside-revit/settings/branches) configured for the main development branches. Without this, GitHub's auto-merge feature doesn't work.

When the new pull request is created, GitHub will trigger a new "test" build (see [main.yml](https://github.com/mcneel/rhino.inside-revit/blob/1.x/.github/workflows/main.yml)). The build uses the "what if" merge commit that GitHub creates for pull requests. If this build passes, the pull request will merge automatically.
