### ISSUE TITLE
Update version numbers

### ISSUE THREAD

**Issue by golsby** [mcneel/rhino.inside-revit#428]
- [x] Set ProductInfo.xml in 1.0 branch to MajorVersion 1, MinorVersion 0
- [x] Set ProductInfo.xml in 1.x branch to MajorVersion 1, MinorVersion 1

**Comment by kike-garbo** [comment]
- [x] Set ProductInfo.xml in 1.0 branch to MajorVersion 1, MinorVersion 0
- [ ] Set ProductInfo.xml in 1.x branch to MajorVersion 1, MinorVersion 1
