### ISSUE TITLE
Add missing component icons for 1.0 release

### ISSUE THREAD

**Issue by eirannejad** [mcneel/rhino.inside-revit#431]

**Comment by kike-garbo** [comment]
- [ ] 'Phase' parameter.
- [ ] 'Define Parameter' component.
- [ ] 'Add Parameter' component.
- [ ] 'Query Parameters' component.
- [ ] 'Shared Parameters' component.
- [ ] 'Global Parameter' component.
- [ ] 'Project Parameter' component.
- [ ] 'Element Parameter' component.
- [ ] 'Parameter Formula' component.

**Comment by eirannejad** [comment]
Done

![Screen Shot 2021-08-06 at 9 56 35 AM](https://user-images.githubusercontent.com/8197916/128545844-f31fb894-391c-466d-8210-c5f7e89efcef.png)
![Screen Shot 2021-08-06 at 9 56 25 AM](https://user-images.githubusercontent.com/8197916/128545846-b06a12b3-201e-47bc-932f-ffbbfddd8b32.png)
![Screen Shot 2021-08-06 at 9 56 18 AM](https://user-images.githubusercontent.com/8197916/128545849-ded75ea9-d645-4992-b21e-f2da921bf1a0.png)
![Screen Shot 2021-08-06 at 9 56 12 AM](https://user-images.githubusercontent.com/8197916/128545851-13df73b2-0c8d-4df9-b7e2-1987e8907c17.png)
