### ISSUE TITLE
Equal Rule Throwing Exemption

### ISSUE THREAD

**Issue by japhyw** [mcneel/rhino.inside-revit#432]
1. Grasshopper: Input parameter index [-1] too low for Component Equals Rule.

Old definitions aren't working with this component, any attempt to compare a value throws an error

https://discourse.mcneel.com/t/input-parameter-index-1-too-low-for-component-equals-rule-error/128273/4

**Comment by kike-garbo** [comment]
Fixed on 7987c61550101819daba3bb417c32c125f4538eb
