### ISSUE TITLE
Set Grasshopper Window Always Top Most

### ISSUE THREAD

**Issue by chuongmep** [mcneel/rhino.inside-revit#437]
**Is your feature request related to a problem? Please describe.**
I think that prioritizing the Grasshopper app over revit like dynamo did would be helpful to a lot of people.

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/31106432/128585252-fd4bee71-9199-46c3-8281-0c10ca776c6b.png)

**Current**
![image](https://user-images.githubusercontent.com/31106432/128585250-11eeb32b-adb6-4195-a877-db3e0f1722a0.png)

**Comment by kike-garbo** [comment]
Added this option.

![image](https://user-images.githubusercontent.com/3530512/139248481-ff6fedf1-e992-4444-843b-52aa03af264e.png)
