### ISSUE TITLE
Include version number into the .msi file name

### ISSUE THREAD

**Issue by kike-garbo** [mcneel/rhino.inside-revit#449]
Some users have problems downloading the file again because the browser cache.

**Comment by pearswj** [comment]
Uh, not again! I think we probably need to update the way we're using the McNeel release system (i.e. https://www.rhino3d.com/download/rhino.inside-revit/7/wip) to eliminate this problem.

**Comment by kike-garbo** [comment]
Rhino download includes language and version name.
`rhino_en-us_7.9.21222.15001.exe`

Can't we do the same for our installer?

**Comment by pearswj** [comment]
The next "stable" release will update the download url at https://www.rhino3d.com/download/rhino.inside-revit/1/latest (hopefully).
