### ISSUE TITLE
Implement 'Query Line Patterns' component

### ISSUE THREAD

**Issue by kike-garbo** [mcneel/rhino.inside-revit#467]
- [x] Add Line Pattern
- [x] Line Pattern Dashes
- [x] Query Line Patterns
- [x] Icons

**Comment by kike-garbo** [comment]
Components need icons:

- [ ] Add Line Pattern
- [ ] Line Pattern Dashes
- [ ] Query Line Patterns

**Comment by eirannejad** [comment]
unknowingly created a different issue for the icons.#483
