### ISSUE TITLE
Feature Request:  Add Assembly Components

### ISSUE THREAD

**Issue by japhyw** [mcneel/rhino.inside-revit#480]
Create Assembly (with Name)
Get List of Assembly Elements
Add Members to Assembly
Remove Members from Assembly
Rename Assembly Type
Place Assembly Instance
Disassemble Assembly

Create Assembly Views Basic (view picker)
Create Assembly Views Advanced  (view type picker, title block, scale & location on sheet)
Create Schedule Basic
Create Schedule Advanced (sheet and location)
Create 3D View
Create 3D View Advanced (sheet and location)

**Comment by eirannejad** [comment]
- [x] Assembly (primitive)
- [x] Add Assembly
- [x] Add Assembly (Location)
- [x] Query Assemblies
- [x] Assembly Members (+/-)
- [x] Explode Assembly 
- [x] Query Assembly Views
- [x] Create Assembly Sheet
