### ISSUE TITLE
Problem with opening the Rhino from Revit

### ISSUE THREAD

**Issue by marcinwoch** [mcneel/rhino.inside-revit#5]
Hello,

Today I installed Rhino Inside and I have a problem with Licence Manager initialization.
Here is a window which shows up:

![2019-09-11_08h55_50](https://user-images.githubusercontent.com/6567040/64674978-56da0600-d472-11e9-8517-75390d7ef032.png)

Also, I tried to open Revit as Administration, but nothing changed.

I attach the error message "RhinoDotNetCrash":

```
[ERROR] FATAL UNHANDLED EXCEPTION: System.AccessViolationException: An attempt was made to read or write protected memory. It often indicates that another memory is damaged.
w Options.setSSOServer(Options* , Int32 )
w UIFrameworkServices.WebServiceWrapperImp.{dtor}(WebServiceWrapperImp* )
w UIFrameworkServices.WebServiceWrapperImp.__delDtor(WebServiceWrapperImp* , UInt32 A_0)
w UIFrameworkServices.WebServiceWrapper.!WebServiceWrapper()
w UIFrameworkServices.WebServiceWrapper.Dispose(Boolean A_0)

[END ERROR]
```

**Comment by eirannejad** [comment]
Please follow these pages and report the issues back to developers
- [Troubleshooting](https://www.rhino3d.com/inside/revit/beta/reference/toubleshooting)
- [Known Issues](https://www.rhino3d.com/inside/revit/beta/reference/known-issues)
