### ISSUE TITLE
Wall Opening Component

### ISSUE THREAD

**Issue by japhyw** [mcneel/rhino.inside-revit#508]
Create a rectangular opening in a wall

https://www.revitapidocs.com/2016/06a216d4-2cf6-ec8f-df5b-10f007b70531.htm

https://discourse.mcneel.com/t/rhino-insiderevit-wall-opening-cuts-for-doors-and-window/131994

**Comment by kike-garbo** [comment]
Closed with 92644ec767d59124128bd6a851072d2df5d0284b
