### ISSUE TITLE
Railing - Top Rail Type Geometry is missing

### ISSUE THREAD

**Issue by japhyw** [mcneel/rhino.inside-revit#509]
Railing Top Rail fails to return geometry in Element Geometry component, as well as Graphical Element and Type Instances.

![image](https://user-images.githubusercontent.com/87487580/138865006-11efc1d9-97e6-41d4-9ee1-8eb8db5a3c63.png)

https://discourse.mcneel.com/t/everybody-is-good/132249/2

**Comment by kike-garbo** [comment]
Well, the top rail is an other element in Revit with a different ID.

You ca use ‘Element Dependents’ filtering ‘TopRail’ objects to get what you need here.

![image](https://user-images.githubusercontent.com/3530512/139110836-2b493a60-c3b5-4bcb-a2f4-d0f1a799edf3.png)

**Comment by kike-garbo** [comment]
Added 'Expand Dependents' to expand dependent elements geometry into the output.

![image](https://user-images.githubusercontent.com/3530512/141833796-cd8bb7a1-8f79-4028-b071-04e58bef4e4f.png)
