### ISSUE TITLE
Ability to Assign Categories when Creating Parameters

### ISSUE THREAD

**Issue by japhyw** [mcneel/rhino.inside-revit#518]
Added feature to assign Categories when creating Parameters 

https://discourse.mcneel.com/t/defining-and-managing-shared-project-parameters/113065/4?u=japhy

https://thebuildingcoder.typepad.com/blog/2014/04/category-support-for-shared-type-and-instance-parameters.html

**Comment by kike-garbo** [comment]
@japhyw,
You can do it using the 'Project Parameter' component.

![image](https://user-images.githubusercontent.com/3530512/142255917-8ed7d151-81f9-47bf-82d1-db79c1b75cae.png)

It allows you to query and modify the parameter categories on new or existing parameters.
