### ISSUE TITLE
Rhino Inside Expecting Radians when Revit wants Degrees

### ISSUE THREAD

**Issue by jbf1212** [mcneel/rhino.inside-revit#53]
For angle parameter values in Revit you typically input a number in degrees. However, the Element.ParameterSet component appears to be expecting angles in radians. It might help to either provide a more clear error message or change the component to accept the format that you would typically use on the Revit side.
![image](https://user-images.githubusercontent.com/16307323/69285071-0f809c00-0bbe-11ea-9f4f-58e61f25a571.png)

**Comment by kike-garbo** [comment]
You are right it may be a bit confusing for Revit users, but all native Grasshopper components that take an angle always take them in radians, so I guess having some components that take degrees and some others that take radians just add more confusion.

There are some components to help in the conversion and make it explicit in the canvas.

![image](https://user-images.githubusercontent.com/3530512/69426181-ec282f00-0d2c-11ea-9775-bb2741a758a3.png)

I will try to improve the error message.
