### ISSUE TITLE
Spatial Nodes

### ISSUE THREAD

**Issue by bimgeek** [mcneel/rhino.inside-revit#533]
Grasshopper inside Revit lacks spatial nodes. Such as creating rooms, getting room boundaries etc. I have created some custom python components but native one would be much more efficient in terms of performance.

![image](https://user-images.githubusercontent.com/51519350/152105351-f44c6d0c-1a92-4abe-9548-93f2f9b9655d.png)

**Comment by kike-garbo** [comment]
- [x] 'Spatial Element Boundary'
- [x] 'Spatial Element Geometry'
- [x] 'Add Space Separation'
- [x] 'Add Room Separation'
- [x] 'Add Area Boundary'
- [x] 'Query Areas'
- [x] 'Query Rooms'
- [x] 'Query Spaces'
- [x] 'Add Area' #500
- [x] 'Add Room" #471
- [x] 'Add Space'
- [x] 'Add Area Tag'
- [x] 'Add Room Tag'
- [x] 'Add Space Tag'

**Comment by bimgeek** [comment]
Rooms by nature require working with them level by level. I think it would be great to have an optional input for level maybe.
