### ISSUE TITLE
Edit Existing Boundary

### ISSUE THREAD

**Issue by bimgeek** [mcneel/rhino.inside-revit#540]
Support for editing boundary-type elements has been added in Revit 2022. Having the option to set boundary of existing revit elements would be great.
https://apidocs.co/apps/revit/2022/8538b361-08df-9fd2-93bb-1790a09130f7.htm

an example use case might be this:
![image](https://user-images.githubusercontent.com/51519350/155127930-e5443560-e156-48eb-b49d-f32ecf5d3bf1.png)
As the image above demonstrates, I have a wall and a beam intersecting with each other. I want to edit the wall profile and exclude the portion that intersects with beam. Final result will be this👇:
![image](https://user-images.githubusercontent.com/51519350/155128182-5682a365-e2ad-408b-be66-ade7ba3af9be.png)
doing this kind of boolean operations between existing elements and updating boundaries of em.

**Comment by kike-garbo** [comment]
Implemented in v1.9

![image](https://user-images.githubusercontent.com/3530512/174667538-9f92f683-c507-4178-bcf9-d73156e7abda.png)
