### ISSUE TITLE
Set domain to Nurbs curve does not work (RawDecoder convert HermiteSpline), used trim instead

### ISSUE THREAD

**Issue by demi-solemma** [mcneel/rhino.inside-revit#546]
https://github.com/mcneel/rhino.inside-revit/blob/877dcadd2eb65e7608f41240afcc880c594cd856/src/RhinoInside.Revit/Convert/Geometry/Raw/RawDecoder.cs#L178

Set domain simply didn't have an effect. 
Also tried setting the domain in a grasshopper conponent of the exported curve... also did not have an effect. 
![image (15)](https://user-images.githubusercontent.com/81834605/155397008-bf3623ae-5d8d-4a53-ac1b-6f28a1c378da.png)

switching the referenced line to the line below worked! 

```C#

            nurbsCurve = nurbsCurve.Trim(hermite.GetEndParameter(0), hermite.GetEndParameter(1)) as NurbsCurve;
```

**Comment by kike-garbo** [comment]
Fixed on https://github.com/mcneel/rhino.inside-revit/commit/ca44828d0f7aecf8a0846edbcdc1682a23cee645
