### ISSUE TITLE
Load Rhino without showing window

### ISSUE THREAD

**Issue by twastvedt** [mcneel/rhino.inside-revit#55]
Is it possible to load Rhino without showing the Rhino window? I think this was working just a bit ago, but now it looks like even when passing `WindowStyle.Hidden` to RhinoCore() the main Rhino window still appears. I'm only working in Revit, so I'm not sure if this is a larger issue, but if so I can repost elsewhere.

**Comment by kike-garbo** [comment]
This will be fixed into the next Release of Rhino.
I keep it open until this happens.
