### ISSUE TITLE
Edit Existing Defining Curves

### ISSUE THREAD

**Issue by japhyw** [mcneel/rhino.inside-revit#587]
User would like a native or scripted component that can Edit existing Revit Element defining Curves; Walls, Floors, Ceilings. 

Input: Revit Element
Input: New Curves
Result: Updated Revit Element.

https://discourse.mcneel.com/t/set-boundary-of-existing-floor/137737/12

**Comment by kike-garbo** [comment]
Implemented in v1.9

![image](https://user-images.githubusercontent.com/3530512/174667538-9f92f683-c507-4178-bcf9-d73156e7abda.png)
