### ISSUE TITLE
Material selector

### ISSUE THREAD

**Issue by scotttd** [mcneel/rhino.inside-revit#59]
Would it be worth getting a Material selector?  A dropdown like FamilyName or TypeName?  Or get a Document.Material component?

Currently this works but is more complicated then necessary:

![image (31)](https://user-images.githubusercontent.com/887876/69586394-4e846800-0f97-11ea-9578-5f0882a22925.png)

**Comment by kike-garbo** [comment]
I added a picker into the context menu.

![image](https://user-images.githubusercontent.com/3530512/69716205-e2764100-1109-11ea-8b68-a82442f89194.png)
