### ISSUE TITLE
Cannot bake into Revit

### ISSUE THREAD

**Issue by ArchitectTaeyoon** [mcneel/rhino.inside-revit#6]
For me, with a certain file at the office - Using the same method as before to bake into Revit doesn't work properly - Revit freezes.
( Toggle to bake - no geometry appears and Revit just freezes. Rhino & Grasshopper are still responsive)

Any advice is appreciated ! :)

![Screenshot (35)](https://user-images.githubusercontent.com/16857323/65973214-d8fe8e80-e462-11e9-9276-4204a6235910.png)

- now starting to have Revit freeze when I simply select geometry for preview in grasshopper.
Doing the same type of operations worked fine before...
-after switching to another grasshopper definition, the Revit came back to life. I'm guessing it depends on the Rhino geometry/file.

**Comment by eirannejad** [comment]
Please follow these pages and report the issues back to developers
- [Troubleshooting](https://www.rhino3d.com/inside/revit/beta/reference/toubleshooting)
- [Known Issues](https://www.rhino3d.com/inside/revit/beta/reference/known-issues)
