### ISSUE TITLE
When editing a component in place I can't pan in Grasshopper

### ISSUE THREAD

**Issue by Intuos5** [mcneel/rhino.inside-revit#609]
**Versions**

> Rhino.Inside: 1.7.8194.7007
> Rhino: 7.18.22124.3001
> Revit: 2023

**Describe the bug**
When I am editing a component in place, it is no longer possible to pan the Grasshopper window using RMB. Instead, it pops-up the RMB click menu. 

**To Reproduce**
1. Start Rhino inside
2. Open Grasshopper, preferably add some components to the canvas
3. Go back to Revit
4. Go to the Architecture tab and go to Component > Model in place to create a new in-place component
5. Go back to Grasshopper and pan the canvas
6. Notice that it only shows the pop-up RMB panel.

**Expected behavior**
I would expect to still be able to pan the Grasshopper. 

**Screenshots**

https://user-images.githubusercontent.com/63149655/174591315-47b032d2-ca4d-48f9-a120-edd1b7045af0.mp4

**Additional context**
Through the same method, using dual monitors, I couldn't manage to snap Grasshopper to the right-hand border of my first monitor, it would simply drag across to the next monitor. 
The RMB menu that pops up, also got stuck on my screen the first time I discovered this problem. It would only go away once I finished the component creation.

**Comment by kike-garbo** [comment]
All Rhino-Grasshopper UI is disabled during any Revit command.
No operation can be done on Revit from an external Add-In either during this time.

Other parts of Revit UI also follows this approach and are disabled.

![image](https://user-images.githubusercontent.com/3530512/174667272-f73be6ef-0137-4d71-98d4-2d0770ea951c.png)

**Comment by Intuos5** [comment]
@kike-garbo I understand. But in that case, could the Rhino viewport and Grasshopper be greyed out so it indicates that you shouldn't and cannot use the windows? That would help to avoid any (accidental) issues.
