### ISSUE TITLE
Periodic Breps do not import

### ISSUE THREAD

**Issue by scotttd** [mcneel/rhino.inside-revit#612]
**Versions**

> Rhino.Inside: 1.7
> Rhino: 7.18
> Revit: 2021

**Describe the bug**
If I try and import this Brep that is periodic then it does not import into a Revit Family. (Upper BREp)  If I explode, Split the periodic surface and join and it imports fine. (lower BRep)

I know that Rhino has a split periodic surface function.  Can we add that into the Geometry pipeline?
[periodic surface split.zip](https://github.com/mcneel/rhino.inside-revit/files/8952528/periodic.surface.split.zip)

**Comment by kike-garbo** [comment]
I tested on RiR 1.9 and Revit 2021.1.2 and works.

![image](https://user-images.githubusercontent.com/3530512/174899261-e64d5434-e2a8-42ea-83a1-1e5ac777912a.png)

**Comment by kike-garbo** [comment]
Also in Revit 2019.2.3

![image](https://user-images.githubusercontent.com/3530512/174900105-f73992cc-447b-43c5-bd77-8d63a8213e52.png)
