### ISSUE TITLE
Set Element Parameter casting issue with enums

### ISSUE THREAD

**Issue by jbf1212** [mcneel/rhino.inside-revit#613]
**Versions**

> Rhino.Inside: 1.6.8.8159.20547
> Rhino: 7.19.22165.13001
> Revit: 2022.1

**Describe the bug**
When attempting to set parameters using the 'Element Parameter' component and the expected value is an enum, Grasshopper seems to be requiring to cast the value input to an Integer type prior to input. For some reason using Integer sliders or typing an integer into a panel no longer works (it used to be fine in older version of RiR). 

**To Reproduce**
1. Attempt to set a parameter requiring an enum input using an integer slider or typing into a panel.
2. See error

**Expected behavior**
Would expect tool to be able to cast from an integer slider (I'm not sure why this integer is different than the converted version).

**Screenshots**
Would expect this to work:
![image](https://user-images.githubusercontent.com/16307323/175117469-5a160608-496e-4d3a-9fc5-936d6805cb4f.png)

Need to do this in order to work:
![image](https://user-images.githubusercontent.com/16307323/175118618-4cf745fc-b05b-423e-b7be-007d0f1decef.png)

**Comment by kike-garbo** [comment]
Fixed in [v1.8.8215.8714](https://github.com/mcneel/rhino.inside-revit/releases/tag/v1.8.8215.8714)
