### ISSUE TITLE
Installation path is not correct and fails installation.

### ISSUE THREAD

**Issue by alexberd** [mcneel/rhino.inside-revit#62]
I tried to install the new RhinoInside MSI released last week and I am getting the following error.
![image](https://user-images.githubusercontent.com/4086522/69655746-236d4780-106f-11ea-9a77-73f96aa17e7b.png)

It seems that two backslashes are defined for the installation path.
Would it be possible to amend and update the MSI ?

**Comment by kike-garbo** [comment]
Could you please update your installer from [here](https://www.rhino3d.com/download/rhino.inside-revit/7/wip), run `msiexec /i RhinoInside.Revit.msi /log RhinoInside.Revit.log` at console and send me back the `RhinoInside.Revit.log` file?

**Comment by kike-garbo** [comment]
Have you tried to generate the log file?

**Comment by alexberd** [comment]
@kike-garbo
Please see the log file created.
[RhinoInside.Revit.log](https://github.com/mcneel/rhino.inside-revit/files/3901293/RhinoInside.Revit.log)

**Comment by kike-garbo** [comment]
I need more information please run `msiexec /i RhinoInside.Revit.msi /l*v RhinoInside.Revit.log` at console and send me back the new `RhinoInside.Revit.log` file again.

Thanks.

**Comment by alexberd** [comment]
@kike-garbo 
See below the new log file created.
[RhinoInside.Revit.log](https://github.com/mcneel/rhino.inside-revit/files/3916411/RhinoInside.Revit.log)
Please, let me know your findings.

**Comment by kike-garbo** [comment]
Could you please try it now?
