### ISSUE TITLE
Paint element faces

### ISSUE THREAD

**Issue by Blame4** [mcneel/rhino.inside-revit#641]
**Is your feature request related to a problem? Please describe.**
*A clear and concise description of what the problem is. Ex. I'm always frustrated when […]*

**Describe the solution you'd like**
some element can not be attached to materials,like CableTray.
so far, the most acceptable way is to paint material to element faces.
I wish to get node to get elemrnt faces in such a way the element geometry did.
and a node to paint material to those faces.

**Describe alternatives you've considered**
*A clear and concise description of any alternative solutions or features you've considered.*

**Additional context**
*Add any other context or screenshots about the feature request here.*

**Comment by kike-garbo** [comment]
So this would be two components:

- [x] 'Deconstruct Element Geometry' component (Queries elements faces and edges)
- [x] 'Element Face Paint' component (Get-Set element face paint material)

**Comment by kike-garbo** [comment]
Implemented in v1.10
