### ISSUE TITLE
Add Spot Coordinate or Elevation References no longer valid.

### ISSUE THREAD

**Issue by japhyw** [mcneel/rhino.inside-revit#651]
RiR 1.10

Tested in 2023 & 2022

**Describe the bug**

In a new revit file create a locked 3D view. Add walls reference one.

![image](https://user-images.githubusercontent.com/87487580/186924684-4afb8f26-4737-4874-8f63-c967171fb13d.png)

Adding a reference by Right Clicking the R input might work, but not on multiple of the same wall. 

1. RhinoInside.Revit.GH: One or more Spot Dimension references are no longer valid.  Spot Dimensions can generally reference only those references which have valid coordinates in the view.

First reported here with an example.

https://discourse.mcneel.com/t/rir-annotations-spot-elevatations-coordinates/147039/4

**Comment by kike-garbo** [comment]
It looks like Revit UI does not allow you to create a Spot Elevation Dimension on vertical faces.

![image](https://user-images.githubusercontent.com/3530512/203860341-09c475ab-f72a-4be5-a52b-36cd06f9d383.png)
