### ISSUE TITLE
Error creating Project Parameter from Shared Parameter File

### ISSUE THREAD

**Issue by japhyw** [mcneel/rhino.inside-revit#655]
1. RhinoInside.Revit.GH: Input groupTypeId is not an identifier of a built-in parameter group.

https://discourse.mcneel.com/t/create-project-parameter-from-shared-parameter-file/148018/2

Confirmed in:

Rhino.Inside Revit: 1.10.8277.18741 (2022-08-30T10:24:42)

Rhino: 7.23.22255.07001 (Rhino 7)
Revit: 2022.1 (22.1.1.516)
CLR: 4.0.30319.42000 (4.8.4515.0)
OS: Microsoft Windows NT 10.0.19044.0

**Comment by kike-garbo** [comment]
Fixed on ecf8b510a4f502f9108a2da6ffc54943c0efff8c
Available since v1.9-RC6
