### ISSUE TITLE
About <active selection> 

### ISSUE THREAD

**Issue by leongoing** [mcneel/rhino.inside-revit#666]
Active selection is a very useful function for Rhino/Revit interaction. Two issues about I found about it listed as below. 
1. <active selection> is not truly "active", it requires a recompute. 
2.<active selection> seems not work for every object. For instance the object showing in the image below can't be active selected. It is a roof in the rac_basic_sample_project in Revit 2021. 
![image](https://user-images.githubusercontent.com/68125661/196014307-866bff7e-1a69-4ee0-8b34-be18ffd6a20d.png)

**Comment by kike-garbo** [comment]
Fixed on v1.10
