### ISSUE TITLE
Build fails - error CS0117

### ISSUE THREAD

**Issue by alexberd** [mcneel/rhino.inside-revit#68]
Trying to build with Visual Studio I am getting the following error

> error CS0117: 'PythonScript' does not contain a definition for 'AddRuntimeAssembly'

![image](https://user-images.githubusercontent.com/4086522/69809228-3dc73280-11e1-11ea-9f25-f6eeee776ea3.png)

There are no references missing, and all Rhino References refer to the latest Rhino WIP installation.
![image](https://user-images.githubusercontent.com/4086522/69809600-f8573500-11e1-11ea-848b-9c14bc4cdc8f.png)

**Comment by kike-garbo** [comment]
Fixed., that line was there by mistake.
Thanks for pointing it out.
