### ISSUE TITLE
New Components to Create and Modify Beam Systems

### ISSUE THREAD

**Issue by japhyw** [mcneel/rhino.inside-revit#680]
https://discourse.mcneel.com/t/structural-beam-system-using-rir/149701

Beam Systems are very useful Revit Elements with lots of potential uses.  Components to be able to create and configure the beam system would be needed. 

https://www.revitapidocs.com/2022/38e7211c-d61b-01fb-7c66-0fca146684a2.htm

**Comment by kike-garbo** [comment]
Added in v1.14
