### ISSUE TITLE
Rhino 7 in Revit will not allow the Help panel to be closed each time Rhino is opened.

### ISSUE THREAD

**Issue by scotttd** [mcneel/rhino.inside-revit#7]
When Opening Rhino 7, the Help Panel is always showing.  I can close all the tabs to the right and close Rhino. Then after restarting Revit and Rhino I get the Help panel back.

Rhino 7 WIP does not do this when started outside Revit.

![image](https://user-images.githubusercontent.com/887876/65465916-50ed0900-de12-11e9-87c3-3ab21ab5acee.png)

**Comment by kike-garbo** [comment]
Is the same issue as #89
