### ISSUE TITLE
New Active Selection component that supports linked document elements as well. 

### ISSUE THREAD

**Issue by japhyw** [mcneel/rhino.inside-revit#711]
User is requesting a component named Active Selection that will similar to a Graphical Element component but with the name Active in the title as well as the ability to selected linked document elements. 

https://discourse.mcneel.com/t/get-elements-in-active-selection/135897/12?u=japhy

**Comment by kike-garbo** [comment]
Unfortunately there is no direct API for get selected linked elements.

**Comment by kike-garbo** [comment]
API is available since Revit 2023.
Done in v1.21
