### ISSUE TITLE
Revit cannot run the external application

### ISSUE THREAD

**Issue by tarabishy2020** [mcneel/rhino.inside-revit#75]
Hi @kike-garbo,

After installing I get this message. Tried using the provided installer and building from source. The same message appears on all Revit versions.

![image](https://user-images.githubusercontent.com/9935834/70054598-c540e700-15cf-11ea-9851-51a212a95bac.png)

[RhinoInside.Revit.log](https://github.com/mcneel/rhino.inside-revit/files/3916826/RhinoInside.Revit.log)

**Comment by kike-garbo** [comment]
Hi,

RiR is trying to install the keyboard shortcuts into your configuration file, to do so it first needs to read the content to add the new one, it is failing reading it.
This file is at `%APPDATA%\Roaming\Autodesk\Revit\Autodesk Revit 2020\KeyboardShortcuts.xml`
It uses to be a KeyboardShortcuts.log as well.

Could you please locate yours on your computer and share it with me?

**Comment by tarabishy2020** [comment]
@kike-garbo only in the Revit 2020 folder I found the .log file but its empty. Attached is the .xml (just renamed in order to upload here)
[KeyboardShortcuts.txt](https://github.com/mcneel/rhino.inside-revit/files/3926401/KeyboardShortcuts.txt)

**Comment by tarabishy2020** [comment]
So for some reason the files were in binary format, deleting them and restarting Revit, re-creates them in the proper format and Inside works.
