### ISSUE TITLE
Add ability to modify Shared Parameter Group before or after adding to the project parameters

### ISSUE THREAD

**Issue by japhyw** [mcneel/rhino.inside-revit#760]
Currently there isn't a way to assign the incoming Shared Parameter to a Group as its definition is added as a project parameter.  Or a way to modify it once its created. 

![image](https://user-images.githubusercontent.com/87487580/212474585-c6a58367-5e57-4099-b87f-47599443a250.png)

**Comment by kike-garbo** [comment]
Parameter Identity component do have a Group input for this purpose.

Is it enough?

**Comment by japhyw** [comment]
Didn't catch that, thanks that will work.

![image](https://user-images.githubusercontent.com/87487580/212490260-87ae7a22-36f3-4e1d-9897-23c36cb5e6d0.png)
