### ISSUE TITLE
Material Graphics component doesn't  Get or Set Foreground Pattern

### ISSUE THREAD

**Issue by japhyw** [mcneel/rhino.inside-revit#764]
Reported on discourse and confirmed in 1.12.8407.24005 and well as the latest daily build 1.13.8417.19563  (Revit 2023)
https://discourse.mcneel.com/t/material-component-error-in-rir-v-1-12-8407-24005-or-above/153465

![image](https://user-images.githubusercontent.com/87487580/213230531-2bcff09a-ff85-4c2e-bcc3-4e46fc16f4b6.png)

**Comment by kike-garbo** [comment]
Fixed on ba09299f9fe96ee7827ddeedd31c9b1b882a74dd
