### ISSUE TITLE
Rhino geometry does not translate into Family

### ISSUE THREAD

**Issue by scotttd** [mcneel/rhino.inside-revit#78]
This Rhino model has two objects and a point.  The rectangular object translates into a family, the fin polysurface does not. 

If I explode and re-join the fin polysurface it will translate. Is there a tolerance issue?  What is the existing join tolerance?

[no-fin.zip](https://github.com/mcneel/rhino.inside-revit/files/3918035/no-fin.zip)

**Comment by scotttd** [comment]
The reason this could not translate was that the fins have an edge less then a mm in length.  This is something Revit does not like.  Here is a thread that contains a utility function that helps find these edges: https://discourse.mcneel.com/t/zero-length-edges/39271/11

**Comment by kike-garbo** [comment]
Now micro-edges are skipped, not passed to Revit.

A micro-edge is an edge shorted tan join-tolerance which in Revit is returned by [`Autodesk.Revit.ApplicationServices.Application.VertexTolerance`](https://apidocs.co/apps/revit/2020/5e064096-daf4-0fcf-65ff-bf058c5b67f5.htm), its value is aprox. **1/160 inch**.

![image](https://user-images.githubusercontent.com/3530512/104919487-9f72cf00-5996-11eb-8753-f94fb5e02537.png)
