### ISSUE TITLE
Add Ability to Get Multiple Face References without the Revit UI

### ISSUE THREAD

**Issue by japhyw** [mcneel/rhino.inside-revit#785]
Currently the only way to get additional faces is to pick via the Revit UI.  

Ideally solved with a new component(s) that could create all possible references (Face,Crv,Point,Ref Plane) of an element 

![image](https://user-images.githubusercontent.com/87487580/214696569-d4828d32-9095-4a2a-8d1a-2859639c6ccc.png)

**Comment by kike-garbo** [comment]
Added on v1.14

**Comment by japhyw** [comment]
Request for additional support for Family Elements. 
https://discourse.mcneel.com/t/element-geometry-reference-get-model-lines/161306

Perhaps this could be a family specific component that would also get Named References as well.

https://github.com/mcneel/rhino.inside-revit/issues/824

**Comment by kike-garbo** [comment]
Added 'Component References' component in v1.16.
