### ISSUE TITLE
Get Named Reference Plane in Family Instance

### ISSUE THREAD

**Issue by japhyw** [mcneel/rhino.inside-revit#824]
https://www.revitapidocs.com/2018/d44a95cc-f2c7-1fa9-9180-fefed6d70ed6.htm

This returns a DB.Reference but doesn't cast to anything usable in the Annotation components. 

Feature request is to add the ability to GetReferenceByName in a Family Instance and be able use the result in Annotation components. 

Currently Annotation References returns a Revit Face instead of Reference Plane. 

![image](https://user-images.githubusercontent.com/87487580/220629203-2704b21d-65c0-48c7-a213-351d5f665ba1.png)

**Comment by kike-garbo** [comment]
Added in v1.16
