### ISSUE TITLE
Grasshopper Revit components disappear

### ISSUE THREAD

**Issue by alfonsomonedero** [mcneel/rhino.inside-revit#86]
This is more a suggestion for Grasshopper but becomes more important with RhinoInside.
When a Grasshopper definition is opened in a computer that does not have the components installed, those boxes disappear.

With RhinoInside, every Revit component will disappear if the script is opened in a Rhino session out of Revit, making it only available for Rhino within Revit.

As you may have noticed, if a Rhino file is opened within Revit environment, the performance of Rhino decreases in comparison with an isolated Rhino session.

It would be very beneficial for future implementation if you could make that when a GH definition with Revit components is opened in a Rhino environment, those components are not lost but rather greyed out, showing is not working but not deleting them.

This would allow designers to move the same script from Revit to Rhino environment for further development regarding non RhinoInside stuff.

**Comment by scotttd** [comment]
Interestingly enough, just yesterday afternoon we released a new Rhino/Grasshopper 7 WIP that has this feature.  I believe some of the Parameter objects still do not stay connected correctly, but you can see it is much closer to your request here. Please download it and give it a try.

**Comment by eirannejad** [comment]
Fixed. Grasshopper (outside Rhino.Inside.Revit) now shows missing components as dashed
