### ISSUE TITLE
Level Filter is not collecting all the expected elements.

### ISSUE THREAD

**Issue by japhyw** [mcneel/rhino.inside-revit#899]
When using Element filter the Structural Framing elements aren't being returned. They have a Reference Level and do Cast to Level properly. 

Replicated on 2022 & 2024

Example files available on the post if needed (placing a beam on a level will replicate) 

https://discourse.mcneel.com/t/filter-by-level-issues-in-rhino-inside-revit-2024/159647

**Comment by kike-garbo** [comment]
From Revit API perspective this element is not on any level but it has its 'Reference Level' parameter pointing to a `Level`.

This Query should work on those cases.

![image](https://github.com/mcneel/rhino.inside-revit/assets/3530512/19168e1d-7910-4707-b500-8f75576a2d0b)

We can embed that logic on 'Level Filter' component, but should all the 'Reference Level' parameters work as well?

![image](https://github.com/mcneel/rhino.inside-revit/assets/3530512/c8e0496a-10ab-468b-a0e7-e0a816a52aa9)

**Comment by kike-garbo** [comment]
Added 'Elevation Filter' on v1.14
