### ISSUE TITLE
Element Type Picker fails to Cast to Type Filter in 2024

### ISSUE THREAD

**Issue by japhyw** [mcneel/rhino.inside-revit#900]
This works in 2022 but fails to cast in 2024

https://discourse.mcneel.com/t/query-filters-by-type-issues-in-revit-2024/159491/2?u=japhy

![image](https://github.com/mcneel/rhino.inside-revit/assets/87487580/f6a4a418-719b-488f-8200-b03e4eeac597)

**Comment by kike-garbo** [comment]
Fixed on v1.14
