### ISSUE TITLE
Workset Helper Nodes

### ISSUE THREAD

**Issue by eirannejad** [mcneel/rhino.inside-revit#92]
A series of helper nodes to query worksets and workset information in a model and to set worksets on elements

![worksets](https://user-images.githubusercontent.com/8197916/71197399-5ce83b80-2246-11ea-996d-6a528f69da42.png)

[worksets.zip](https://github.com/mcneel/rhino.inside-revit/files/3984950/worksets.zip)

**Comment by kike-garbo** [comment]
- [x] Add `Types.Workset`
- [x] Add 'Workset' parameter.
- [x] Add 'Query Worksets' component.
- [x] Add 'Element Workset' component.
- [x] Add 'Active Workset' component.
- [x] Add 'Workset Identity' component.
- [x] Add 'Workset Filter' component.
