### ISSUE TITLE
Extracting Family Instance Geometry by SubCategory

### ISSUE THREAD

**Issue by eirannejad** [mcneel/rhino.inside-revit#93]
RE https://discourse.mcneel.com/t/filter-by-sub-category/93907/5?u=eirannejad

Example of Grasshopper definition on how to get geometry (Revit API and Rhino Breps) from a family instance based on the selected subcategory

![Element Geom By Category](https://user-images.githubusercontent.com/8197916/71299162-d2d0cd80-2340-11ea-81cb-b6aa88e342ff.png)

[instace geometry by subcategory.zip](https://github.com/mcneel/rhino.inside-revit/files/3990733/instace.geometry.by.subcategory.zip)

**Comment by kike-garbo** [comment]
This is already possible using the 'Element Geometry' component.

![image](https://user-images.githubusercontent.com/3530512/98145048-f9511600-1eca-11eb-811f-c8135da82fdb.png)
