### ISSUE TITLE
Do not pull geometry from "Not Placed" or "Not Bounded" spatial elements

### ISSUE THREAD

**Issue by michaldengusiak** [mcneel/rhino.inside-revit#99]
I have a model with 3 spaces and one is `Not Placed`

![image](https://user-images.githubusercontent.com/26113670/72065886-2c407280-32d7-11ea-8680-bbd49fdd681d.png)

when I load in GH I can see geometry for all 3 spaces rather than two
![image](https://user-images.githubusercontent.com/26113670/72065971-5eea6b00-32d7-11ea-9f92-09469f9fe5de.png)
![image](https://user-images.githubusercontent.com/26113670/72065994-6c075a00-32d7-11ea-8b32-106e6fdb5e6a.png)

however, I can see also Brep for unplaced space this should be null
![image](https://user-images.githubusercontent.com/26113670/72066177-d4563b80-32d7-11ea-9cfb-f8b085fa1b6a.png)

I guess the best way to use Area parameter
![image](https://user-images.githubusercontent.com/26113670/72067258-3021c400-32da-11ea-8551-79d7898a4292.png)

**Comment by kike-garbo** [comment]
Now that we have 'Query Rooms' and 'Query Spaces' that tale care of unplaced elements this issue is obsolete.
